c9s/bbgo

- pkg/cmd/pnl.go
- pkg/service/trade.go
- pkg/service/trade_test.go
Usage: `bbgo pnl --exchange max --symbol BTCUSDT --limit 7000`
To calculate profit and loss for specified limit of orders
> feat: add limit option for pnl command

- pkg/exchange/max/maxapi/restapi.go
- pkg/util/http_response.go
- pkg/util/http_response_test.go
The `Response` struct is general and could be shared with other exchange implementations, like FTX integration. I move it to util package and add unit test on it.
> minor: move maxapi.Response to util package

- pkg/exchange/max/stream.go
in pkg/exchange/max/stream.go:
```
func convertWebSocketTrade(t max.TradeUpdate) (*types.Trade, error) {
// skip trade ID that is the same. however this should not happen
var side = toGlobalSideType(t.Side)
```
We should use global side here, not string based side.
> fix(max): use global trade side here, not string

- pkg/strategy/bollgrid/strategy.go
剛剛發現之前的 PR 不小心把 `quoteBalance = quotaBalance.Sub(quotaQuantity)` 寫成 `quoteBalance = quotaQuantity.Sub(quotaQuantity)`，造成每次都只會生出一張單，現在修好了～
> Fix bollgrid balance calculation

- pkg/bbgo/order_execution.go
add yaml tag for mapping basic risk control order executor.
> add yaml tag for mapping basic risk control order executor.

- pkg/types/orderbook.go
- pkg/types/orderbook_test.go
The original implementation always returns an error even if the orderbook prices are correct.
> fix: fix orderbook valudation logic 

- pkg/strategy/grid/strategy.go
In the two functions `generateGridSellOrders` and `generateGridBuyOrders`, the conditions `s.LowerPrice <= price` and `price <= s.UpperPrice` are always true. So I think they can be deleted.
> Remove unused conditions when generating orders

- pkg/exchange/ftx/stream_message_handler.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
Verify the orderbook snapshot checksum. However there's a bug of order update checksum. I'm not sure if I have to maintain the whole orderbook or just verify the update message. But it's not an important issue. Let's do that next time.
> feature: orderbook snapshot checksum

- pkg/cmd/root.go
This path will allow telegram user use auth token to attach session
> fix: typo of telegram bot auth token

- README.md
- pkg/backtest/exchange.go
- pkg/backtest/matching.go
- pkg/bbgo/active_book.go
- pkg/bbgo/environment.go
- pkg/bbgo/scale.go
- pkg/exchange/binance/stream.go
- pkg/exchange/max/maxapi/websocket.go
- pkg/exchange/max/maxapi/websocketservice_callbacks.go
- pkg/exchange/max/stream.go
- pkg/service/deposit.go
- pkg/service/withdraw.go
- pkg/strategy/grid/strategy.go
- pkg/types/order.go
- pkg/types/ordermap.go
- pkg/types/side.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
1. 修正重新連線會重新掛單的問題
2. 利用三種參數 price band + side + catchUp 這樣就可以完整建立建倉區間，讓使用者可以選擇一開始只做一邊的單
side 就是一開始只掛一邊，買單或是賣單
搭配 side 的話， price band (upper price ~ lower price) 就會變成建倉價位區間或是平倉價位區間
side + catchUp 就是如果我只掛買，但是價格往上漲，只要在價格範圍內，就會把網格往上補，在一直往上漲的行情，還是可以利用價格調整建立部位。
譬如說你 USDT/TWD 建倉要在 28.0~28.5，如果現價本來在 28.3，網格會掛買單到 28.3，如果又繼續漲，就會自動補單，最高就追補單到 28.5 就不再追買，回調後，買到的部位會立刻套利。
設定範例:
```yaml
- on: max
grid:
symbol: USDTTWD
scaleQuantity:
byPrice:
linear:
domain: [28.0, 28.8]
range: [12.0, 10.0]
gridNumber: 80
profitSpread: 0.06
upperPrice: 28.8
lowerPrice: 28.0
long: true
side: buy
catchUp: true
```
可以用線性 (linear) 或是 對數 (exp) 去分散價量，
這樣高價可以掛少，低價掛多。
> feature: add more grid parameters and options

- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/rest_order_request.go
- pkg/exchange/ftx/rest_responses.go
The time range precision is second, so I will always -1 second to query next page data. I dedupe by created-at and order ID. Note that if the order status is not `closed`, I will skip the order. Please help me to ensure the logic. Thanks.
> feature: query closed orders

- pkg/cmd/balances.go
The current `balances` command needs to be executed with the `--config <config_file>`, but the config file is NOT needed to create the session. So I delete the code which reads the config file. In this way, you can get the balance by running `bbgo balances --session=max`.
> Remove --config argument in balances command

- pkg/backtest/matching.go
- pkg/bbgo/config.go
- pkg/cmd/account.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/rest.go
- pkg/exchange/ftx/rest_account_request.go
- pkg/exchange/ftx/rest_responses.go
- pkg/types/account.go
Note that the make/taker fee on FTX will be a very small number, so I modify the bps type from int to float. For example, your maker fee may be 2.5 bps.
> feature: support FTX account information api

- pkg/backtest/matching.go
- pkg/bbgo/config.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/types/account.go
The fractional part of FTX fee is 8 digits, so it's better to store and calculate by fixedpoint.
> refactor: use fixedpoint to store fee

- pkg/exchange/binance/exchange.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/max/exchange.go
this could make the fee calculation easier, we will just present the precentage.
> REFACTOR: remove bps from the fee calc #1

- pkg/cmd/deposit.go
- pkg/cmd/orders.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/rest.go
- pkg/exchange/ftx/rest_order_request.go
- pkg/exchange/ftx/rest_wallet_request.go
I forgot to assign query string, so I use default values of all GET operations.
Note that I also support the `lastOrderID` in the `QueryClosedOrders`. Please check the logic again thanks.
> fix:add missing query string

- pkg/cmd/trades.go
- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/rest.go
- pkg/exchange/ftx/rest_fills_request.go
- pkg/exchange/ftx/rest_responses.go
FTX trades API doesn't support pagination natively, so we have to split the time range into smaller slices. Please help me verify the logic. I hope there's no infinite loop XD
> feature: query ftx trades

- pkg/exchange/binance/exchange.go
Binance does not allow submitting order without TimeInForce set for
certain order types. Set TimeInforce to GTC (Good-Til-Cancel) by
default.
> binance: set TimeInForce to GTC by default

- pkg/strategy/bollgrid/strategy.go
- pkg/strategy/grid/strategy.go
當 `orderExecutor.SubmitOrders(orders...)` 發生錯誤時，其中有一些 order 可能還是被成功送出了，所以前兩個 commit 把 grid 跟 bollgrid 裡面的 `createdOrders` 都加入追蹤
而第三個 commit 是把 bollgrid 裡面送出 sell orders 跟 buy orders 的部分分開，因為如果把 `[sellOrders..., buyOrders...]` 一起送出，當 sellOrders 裡面有任何一筆送出失敗了（可能訂單金額太小、餘額不足等等），那 buyOrders 就完全不會被送出去。但如果 sellOrders 是因為餘額不足而送出失敗，那 buyOrders 其實還是可以正常送出，所以這邊把他們分開送
> Track created orders when error occurs

- migrations/mysql/20210416230730_klines_symbol_length.sql
Originally the length of symbol column in MySQL is 7 (VARCHAR(7)). However, we have the SANDUSDT and LINKUSDT trading pairs, which is longer than 7 characters.
> migration: extend symbol column length to 10

- migrations/mysql/20210421091430_increase_symbol_length.sql
- migrations/mysql/20210421095030_increase_decimal_length.sql
- pkg/migrations/mysql/20210416230730_klines_symbol_length.go
- pkg/migrations/mysql/20210421091430_increase_symbol_length.go
- pkg/migrations/mysql/20210421095030_increase_decimal_length.go
The volume amount between 4/12 to 4/20 has been increased above the original design of 16 digits. Increase it to 20.
Also symbol length might not be able to hold some new currency pairs like ALICEUSDT or AUCTIONBUSD(11). Increase the length to 12 to be able to hold longer symbol pairs.
> Extend volume and symbol size for DOGEUSDT in binance

- pkg/strategy/bollgrid/strategy.go
profit orders shouldn't be canceled on graceful exit unless
properly persisted.
Issue: #220
> fix(bollgrid): skip canceling profit orders on graceful exit

- pkg/bbgo/active_book.go
Resolve #229 by detecting empty quantity updates on New.
> Fix: binance's cancel update is sent through New status with 0 quantity

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/parse_test.go
Let JSON parse to be explicit for prevent Unmarshal case-insensitive issue
ref: https://golang.org/pkg/encoding/json/#Unmarshal
Resolve #229
> Fix: Correct the binance executionReport parser

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
Resolve #229 
The root cause was the order FILLED event did not be triggered. So, the order did not be completed and the grid did not run correctly.
I found some document. I think the FILLED was part of `TRADE` in `execution type`.
> TRADE - Part of the order or all of the order's quantity has filled.
> Order Status: `FILLED`  -> The order has been completed.
ref: https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md
ref: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#enum-definitions
FILLED with TRADE type
```json
{
"e": "executionReport",
"E": 1620827285499,
"s": "DOGEUSDT",
"c": "x-NSUYEBKMe6596f86-90cb-4fb3-8ea",
"S": "BUY",
"o": "LIMIT",
"f": "GTC",
"q": "40.00000000",
"p": "0.49250000",
"P": "0.00000000",
"F": "0.00000000",
"g": …
```
> Fix: Correct the Order FILLED event on binance

- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/stream.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
ftx uses BTC/USDT symbol styles, however bbgo uses the BTCUSDT style
We setup a mapping table in Markets() to make conversion
> fix(ftxExchange): setup a symbol mapping table

- pkg/bbgo/session.go
- pkg/exchange/binance/depthframe.go
if not ok, `inc` will be `nil`. Should not use `:=` in this case, otherwise the original `inc` will still be `nil` and returned back.  
add stoch indicator creating function.
also fix the error format when depth is not loaded
> Fix: nil pointer exception in indicator creation, add stoch util func

- pkg/exchange/max/maxapi/account.go
maxapi/account.go
type Deposit struct {
...
Confirmations   String  `json:"confirmations"` ->  Confirmations   int64  `json:"confirmations"`
...
}
> fix type change on max api

- pkg/strategy/grid/strategy.go
if the program launched with tokens, it will sell the token with grid price. but it should take care of ProfitSpread to make sure it's working as epected for adding ProfitSpread  for buying price assumption.
> fix generateGridSellOrders with ProfitSpread for begining

- doc/build-from-source.md
-x so the user can see the progress more clearly
main instead of latest because using latest caused commits not to be seen
> Change installation command based on comments in telegram with @c9s

- pkg/exchange/ftx/exchange.go
add ratelimit 
see #334 for more details
> ftx : fix #334 rate limit

- pkg/accounting/pnl/avg_cost.go
- pkg/bbgo/session.go
- pkg/bbgo/tradecollector.go
- pkg/bbgo/tradecollector_callbacks.go
- pkg/bbgo/twap_order_executor.go
- pkg/strategy/bollpp/strategy.go
- pkg/strategy/grid/strategy.go
- pkg/strategy/support/strategy.go
- pkg/strategy/xmaker/strategy.go
- pkg/types/position.go
- pkg/types/position_test.go
1st part of #333 to support binance futures.
```
renamed:    pkg/bbgo/position.go -> pkg/types/position.go
renamed:    pkg/bbgo/position_test.go -> pkg/types/position_test.go
```
```
modified:   pkg/accounting/pnl/avg_cost.go
modified:   pkg/bbgo/session.go
modified:   pkg/bbgo/tradecollector.go
modified:   pkg/bbgo/tradecollector_callbacks.go
modified:   pkg/bbgo/twap_order_executor.go
modified:   pkg/strategy/bollpp/strategy.go
modified:   pkg/strategy/grid/strategy.go
modified:   pkg/strategy/support/strategy.go
modified:   pkg/strategy/xmaker/strategy.go
modified:   pkg/types/position.go
modified:   pkg/types/position_test.go
```
> types: refactor Position and related files

- pkg/exchange/binance/convert.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
No.3 part of #333 to support binance futures.
1. binance: add user stream event parser & toGlobalType converter
```
modified:   pkg/exchange/binance/parse.go
modified:   pkg/exchange/binance/convert.go
```
2. binance: add exchange futures  client stream connection
```
modified:   pkg/exchange/binance/exchange.go
modified:   pkg/exchange/binance/stream.go
modified:   pkg/exchange/binance/stream_callbacks.go
```
> binance: parse OrderTrade event stream & add futures client connection

- pkg/bbgo/session.go
- pkg/exchange/binance/convert.go
- pkg/exchange/binance/exchange.go
- pkg/types/margin.go
No.4 part of #333 to support binance futures.
1. bbgo: add session Futures & types: add FuturesExchange
```
modified:   pkg/bbgo/session.go
modified:   pkg/types/margin.go
```
2. binance: add SubmitFuturesOrder and related conversions
```
modified:   pkg/exchange/binance/convert.go
modified:   pkg/exchange/binance/exchange.go
```
> binance: support submit futures order

- go.mod
- go.sum
- pkg/exchange/binance/convert.go
- pkg/exchange/binance/exchange.go
No.5 part of #333 to support binance futures.
binance: add query orders & trades 
```
modified:   pkg/exchange/binance/convert.go
modified:   pkg/exchange/binance/exchange.go
```
> binance: read orders & trades and add related conversions

- pkg/types/account.go
- pkg/types/margin.go
- pkg/types/position.go
1. types: add FuturesAccountInfo
```
modified:   pkg/types/account.go
```
2. types: add FuturesUserAsset
```
modified:   pkg/types/margin.go
```
3. types: add PositionRisk
```
modified:   pkg/types/position.go
```
> types: add global structs for futures

- pkg/exchange/binance/convert.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
- pkg/types/account.go
- pkg/types/position.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
not implement yet:
1. OrderTradeUpdateEvent `case "TRADE"`
2. OrderTradeUpdateEvent `case "CALCULATED - Liquidation Execution"`
> binance: add futures stream

- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/convert_test.go
- pkg/exchange/ftx/exchange.go
According [FTX document](https://docs.ftx.com/#place-order), it should use `postOnly` and `ioc` to support `LIMIT_MAKER` and 
`IOC_LIMIT `
I create the `toLocalOrderType` method for mapping ftx order.
PS. Still not support `STOP_LIMIT` and `STOP_MARKET`
> ftx: Support LIMIT_MAKER and IOC_LIMIT order type

- pkg/backtest/matching.go
resolve #431   
cc. @arthurwolf 
if the order is sent as market order, it will fetch lastprice as price of the order
however, there's rarely having trade happening inside btc pairs, so lastprice might not been updated for the first tick
> fix: #431 for not updating lastPrice if no tade happened

- pkg/exchange/binance/parse.go
Issue:
[0002]  INFO submitting order: SubmitOrder ETHUSDT LIMIT SELL 0.005000 @ 3002.700000
[0105]  INFO TRADE binance ETHUSDT SELL 500000 @ 300270000000 amount 500000 fee 300270 USDT orderID 8389765515765757063 Feb 12 03:33:32.628 session=binance
> Fix: precision of futures trade data is incorrect.

- pkg/bbgo/session.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/exchange_test.go
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
- pkg/types/channel.go
- pkg/types/exchange.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
and update session.lastPrice accordingly.  
in backtest still doesn't work.  
also the field in market trade is very different from private trade. 
some fields in types.Trade is filled with dummy messages.
one missing part in types/exchange.go is added (the kucoin verification)
> feature: add market trade subscription in binance

- pkg/exchange/binance/convert.go
- pkg/strategy/bollmaker/strategy.go
example config
```
persistence:
redis:
host: 127.0.0.1
port: 6379
db: 0
sessions:
binance-futures:
exchange: binance
futures: true
sync:
userDataStream:
trades: true
filledOrders: true
since: 2019-11-01
sessions:
- binance-futures
symbols:
- BTCUSDT
exchangeStrategies:
- on: binance-futures
bollmaker:
symbol: BTCUSDT
interval: 1m
amount: 60
askSpread: 0.1%
bidSpread: 0.1%
minProfitSpread: 0.1%
useTickerPrice: true
dynamicExposurePositionScale:
byPercentage:
exp:
domain: [ -1, 1 ]
range: [ 0.1, 0.005 ]
uptrendSkew: 0.2
downtrendSkew: 1.5
long: false
buyBelowNeutralSMA: true
tradeInBand: true
defaultBollinger:
interval: "1d"
window: 21
bandWidth: 2.0
neutralBollinger:
interval: "5m"
window: 21
bandWidth: 2.0
persistence:
type: redis
```
> strategy: add bollmaker futures support

- config/ewo_dgtrd.yaml
- pkg/indicator/atr.go
- pkg/indicator/atr_test.go
- pkg/strategy/ewoDgtrd/strategy.go
add atr stoploss for ewo strategy.
fix some filter condition
result: 
```log
BINANCE MATICUSDT PROFIT AND LOSS REPORT
[0017]  INFO TRADES SINCE: 2022-04-14 23:30:59.999 +0900 JST
[0017]  INFO NUMBER OF TRADES: 3
[0017]  INFO AVERAGE COST: $ 1.41
[0017]  INFO TOTAL BUY VOLUME: 7783.49108117
[0017]  INFO TOTAL SELL VOLUME: 8283.49108117
[0017]  INFO STOCK: -500
[0017]  INFO CURRENT PRICE: $ 1.25
[0017]  INFO CURRENCY FEES:
[0017]  INFO  - USDT: 0
[0017]  INFO  - MATIC: 0
[0017]  INFO PROFIT: $ 266.83
[0017]  INFO UNREALIZED PROFIT: $ 76.50
[0017]  INFO INITIAL BALANCES:
[0017]  INFO  MATIC: 500
[0017]  INFO  USDT: 10000
[0017]  INFO FINAL BALANCES:
[0017]  INFO  USDT: 10959.1554423 (locked 11.67523662)
[0017]  INFO INITIAL ASSET IN USDT ~= …
```
> feature: add atr stoploss on ewoDgtrd strategy

- migrations/mysql/20220512170322_fix_profit_symbol_length.sql
- migrations/sqlite3/20220512170330_fix_profit_symbol_length.sql
- pkg/migrations/mysql/20220512170322_fix_profit_symbol_length.go
- pkg/migrations/sqlite3/20220512170330_fix_profit_symbol_length.go
This change fixes "Error 1406: Data too long for column 'symbol' at row 1" for pair symbol longer than 8 chars.
Fixes #608
> Fix error: Data too long for profits column 'symbol'

- pkg/exchange/ftx/exchange.go
FTX resolution field already support 4 hr interval. Just add missing type: Interval4h.
> ftx: Let FTX support 4hr interval

- Dockerfile
go get in 1.18 without go.mod is deprecated
> fix: change from go get to go install in Dockerfile

- scripts/setup-bollgrid.sh
According to the readme, we could set up the config by passing an exchange name.
https://github.com/c9s/bbgo#install-from-binary
I also found the same setup scripts not mentioned in the readme with a fixed exchange name. Should we also modify them?
```
scripts/setup-bollgrid-dnum.sh
48:MAX_API_KEY=$api_key
scripts/setup.sh
92:export MAX_API_KEY=$api_key
scripts/setup-dnum.sh
92:export MAX_API_KEY=$api_key
scripts/setup-bollmaker.sh
48:BINANCE_API_KEY=$api_key
```
> fix: setup-bollgrid.sh: respect exchange name from command line argument

- README.md
- config/supertrend.yaml
- doc/README.md
- doc/strategy/supertrend.md
- pkg/cmd/builtin.go
- pkg/strategy/supertrend/strategy.go
```
START TIME: Fri, 01 Apr 2022 00:00:00 UTC
END TIME: Sat, 30 Apr 2022 00:00:00 UTC
INITIAL TOTAL BALANCE: BalanceMap[BTC: 100, USDT: 10000]
FINAL TOTAL BALANCE: BalanceMap[BTC: 100.00108121, USDT: 10221.17915601]
binance BTCUSDT PROFIT AND LOSS REPORT
TRADES SINCE: 2022-04-01 01:58:59.999 +0000 UTC
NUMBER OF TRADES: 12
AVERAGE COST: $ 39,324.93
TOTAL BUY VOLUME: 1.44164431
TOTAL SELL VOLUME: 1.4405631
CURRENT PRICE: $ 38,596.11
CURRENCY FEES:
- USDT: 45.55325269
- BTC: 0.00108121
PROFIT: $ 274.20
UNREALIZED PROFIT: $ 0.00
INITIAL ASSET IN USDT ~= 4561035.00000 USDT (1 BTC = 45510.35)
FINAL ASSET IN USDT ~= 3869873.90965 USDT (1 BTC = 38596.11)
REALIZED PROFIT: +274.19909983 …
```
> strategy: add supertrend strategy

- config/pivotshort-ETHUSDT.yaml
- config/pivotshort-GMTBUSD.yaml
- config/pivotshort.yaml
- config/pivotshort_optimizer.yaml
- pkg/backtest/exchange.go
- pkg/bbgo/activeorderbook.go
- pkg/bbgo/notifier.go
- pkg/bbgo/smart_stops.go
- pkg/cmd/backtest.go
- pkg/cmd/root.go
- pkg/cmd/run.go
- pkg/fixedpoint/convert.go
- pkg/service/backtest.go
- pkg/strategy/ewoDgtrd/strategy.go
- pkg/strategy/pivotshort/strategy.go
- pkg/strategy/xmaker/strategy.go
- pkg/types/position.go
```
START TIME: Fri, 01 Apr 2022 00:00:00 UTC
END TIME: Wed, 08 Jun 2022 00:00:00 UTC
INITIAL TOTAL BALANCE: BalanceMap[ETH: 10, USDT: 3000]
FINAL TOTAL BALANCE: BalanceMap[ETH: 0.05250783, USDT: 35872.95613945]
binance ETHUSDT PROFIT AND LOSS REPORT
TRADES SINCE: 2022-04-05 23:51:59.999 +0000 UTC
NUMBER OF TRADES: 22
AVERAGE COST: $ 1,907.45
BASE ASSET POSITION: -10.00000562
TOTAL BUY VOLUME: 70.05253372
TOTAL SELL VOLUME: 80
CURRENT PRICE: $ 1,814.21
CURRENCY FEES:
- USDT: 132.10289997
- ETH: 0.05253934
PROFIT: $ 13,905.81
UNREALIZED PROFIT: $ 932.38
INITIAL ASSET IN USDT ~= 35815.1000 USDT (1 ETH = 3281.51)
FINAL ASSET IN USDT ~= 35968.2163 USDT (1 ETH = 1814.21)
REALIZED …
```
> strategy pivotshort: refactor and add stop EMA

- pkg/server/routes.go
The syncing operation is protected by the mutex, so only one goroutine can sync the history. We shouldn't start new goroutines when our previous syncing operation is not done yet. It causes a memory leak.
> fix: syncing goroutine leak

- frontend/.prettierignore
- frontend/.prettierrc.json
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/yarn.lock
It's important to have consistent coding styles in our repo. We don't have default formatter for typescript, so I install `prettier` to format our code. I only apply the single quote rule. We can configure the rule in the future.
We can execute `yarn prettier` to format them.
> feature: add prettier to format the typescript code

- pkg/fixedpoint/dec.go
- pkg/fixedpoint/dec_test.go
issues happen when float is between 0.x to 0.0x
> fix: fixedpoint percentage bound check

- frontend/components/AddExchangeSessionForm.js
- frontend/components/ConfigureDatabaseForm.js
- frontend/components/ConfigureGridStrategyForm.js
- frontend/components/ConnectWallet.js
- frontend/components/ExchangeSessionTabPanel.js
- frontend/components/ReviewSessions.js
- frontend/components/ReviewStrategies.js
- frontend/components/SaveConfigAndRestart.js
- frontend/components/SideBar.js
- frontend/components/TotalAssetsDetails.js
- frontend/components/TotalAssetsPie.js
- frontend/components/TotalAssetsSummary.js
- frontend/components/TradingVolumePanel.js
- frontend/layouts/DashboardLayout.js
- frontend/layouts/PlainLayout.js
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/pages/_document.js
- frontend/pages/connect/index.js
- frontend/pages/index.tsx
- frontend/pages/orders.js
- frontend/pages/setup/index.js
- frontend/pages/trades.js
- frontend/src/theme.js
- frontend/yarn.lock
The v4 is out of date for a long time, so I follow the migration guide to upgrade it from v4 to v5 (https://mui.com/material-ui/migration/migration-v4/). However, I don't have any orders or trades. If you have time, maybe you can check out this branch to see the v5 UI.
> upgrade material UI from v4 to v5.8.3

- frontend/api/bbgo.ts
- frontend/components/SyncButton.tsx
- frontend/hooks/useInterval.ts
- frontend/layouts/DashboardLayout.js
- frontend/pages/_app.tsx
Currently we block the whole page when the server is syncing. But actually we don't have to invoke sync API for some tabs, like strategy. Therefore, I remove the blocking dialog. We should be able to open the strategy page even if the syncing operation is not done yet.
The first time we enter the bbgo frontend page, it invokes the asynchronous sync API first. When we click the order or trade tab, it will query the orders/trades from bbgo API. It's reasonable not to receive whole data since the orders and trades are inserted anytime. it's not possible to always have latest data if bbgo only provides REST API.
So the logic is the same as previous implementation. 
Also, you can trigger the syncing anytime by click the sync button #715
> Do not block whole page while syncing

- pkg/server/routes.go
I haven't noticed the syncing status is defined as 0 in constructor, so the sync goroutine is never initialized. I fix the guard.
> fix: sync api guard condition

- pkg/depth/buffer.go
- pkg/depth/buffer_test.go
- pkg/slack/slackstyle/style.go
avoid using defer lock since it's slower
https://colobu.com/2019/01/22/Runtime-overhead-of-using-defer-in-go/
> fix: depth: do not test depth buffer when race is on

- Dockerfile
- pkg/service/totp.go
There's no `USER` env var in alpine image, causes the program throws error 'No USER or USERNAME' in containers.
* Create and assign `USER` env var in bbgo image
* Fallback to use the default user 'bbgo' when env `USER` or `USERNAME` was unassigned
> totp-user: add default user 'bbgo'

- go.sum
- pkg/optimizer/grid.go
If TotalProfitMetricValueFunc is given summaryReport as nil, the optimizer used to crash. This prevent the optimizer from crashing, and returns 0 (fixedpoint.Zero). In addition, the parameters used while the would crash can be seen in the log.
> optimizer/fix: prevent from crashing if missing SummaryReport

- pkg/cmd/pnl.go
Since the market is essential to calculate the netProfit correctly, so I create the market from the given symbol and pass it to the calculator.
> Fix pnl command

- pkg/cmd/optimize.go
- pkg/optimizer/grid.go
> feature: optimizer: support --tsv option and render tsv output

- pkg/optimizer/grid.go
The progress bar should increase along with task completion instead of report calculation. According to the existing function logic, the optimizer finishes only when progress bar reaching 200%.
> optimizer: correct progress bar counter & ETA calculation

- pkg/cmd/optimize.go
- pkg/optimizer/local.go
In current design, optimizer launches `bbgo backtest` as subprocesses, and these processes will apply DB migration during `DatabaseService` initialization. However, if the optimizer is launched with an empty database, the migrations in these subprocesses would apply their own migration and conflict. There are some ways to prevent such situation:
1. Check the DB before launching backtests, and tip user to execute `bbgo backtest --sync --sync-only` before grid searching logic.
2. Trigger DB sync before backtests. Implemented by this PR.
In addition, to the second approach, maybe it would be more convenient to provide `--sync-from` option to user?
> optimizer: prepare database before executing backtests

- pkg/backtest/report.go
The final asset should be
> quote + balance * _last_price_
Instead of
> quote + balance * _start_price_
> backtest: correct final asset calculation

- pkg/optimizer/grid.go
Currently we queue the backtest tasks in a buffered channel, and enqueue all the tasks before execution. This will cause deadlock if the number of grid points more than 10,000. In this PR, it generate tasks asynchronously on another goroutine, hence the deadlock won't happen.
This PR replaces #828
> optimizer: eliminate limitation of number of grid point

- config/pivotshort.yaml
- pkg/bbgo/exit_cumulated_volume_take_profit.go
- pkg/bbgo/standard_indicator_set.go
- pkg/indicator/pivot_low.go
- pkg/risk/account_value.go
- pkg/strategy/pivotshort/breaklow.go
- pkg/strategy/pivotshort/resistance.go
```
symbol: ETHUSDT
winningRatio: "0.96296296"
numOfLossTrade: 27
numOfProfitTrade: 26
grossProfit: "31685.53749875"
grossLoss: "-5011.38425128"
profits:
- "23.90000000"
- "1.59999990"
- "6880.39999990"
- "24.92150000"
- "29.40000000"
- "16.59999999"
- "2015.00000000"
- "8.29999980"
- "20.60000000"
- "12.00000000"
- "30.70000000"
- "276.80000000"
- "6675.50000000"
- "14.89999990"
- "21.00000000"
- "22.79999990"
- "1747.30000000"
- "2.55799979"
- "26.29999999"
- "24.60000000"
- "29.90000000"
- "10716.39999990"
- "146.24999989"
- "1490.34999989"
- "175.20000000"
- "1252.25799990"
losses:
- "-18.10000000"
- "-383.10000010"
- "-19.09999999"
- "-0.72650020"
- "-202.20000000"
- "-208.20000000"
- "-203.90000000"
- "-263.80000000"
- "-270.10000010"
- "-267.20000000"
- "-248.70000000"
- …
```
> strategy/pivotshort: refactor breaklow + add fake break stop

- pkg/optimizer/grid.go
Calculate the equity value difference as an indicator of optimization.
> optimizer: print equity diff in final report

- config/drift.yaml
- config/driftBTC.yaml
- pkg/bbgo/config_test.go
- pkg/bbgo/session.go
- pkg/bbgo/testdata/strategy.yaml
- pkg/exchange/ftx/exchange.go
- pkg/types/exchange.go
Reduce the order amount to prevent submit rejection because of balance exceeding.
submit_amount = original_amount / (1 + fee_rate)
Currently supported only by FTX Pro.
This PR replaces #859
> exchange: order fee-amount protection

- pkg/bbgo/exit_trailing_stop.go
trailing stop of type both is similar to type buy with short position, type sell with long position
> fix: trailing stop properly works on both long and short positions

- apps/backtest-report/components/TradingViewChart.tsx
- config/drift.yaml
- config/driftBTC.yaml
- go.mod
- go.sum
- pkg/bbgo/interact.go
- pkg/bbgo/notification.go
- pkg/bbgo/order_executor_general.go
- pkg/bbgo/order_store.go
- pkg/indicator/fisher.go
- pkg/notifier/slacknotifier/slack.go
- pkg/notifier/telegramnotifier/telegram.go
- pkg/strategy/drift/driftma.go
- pkg/strategy/drift/output.go
- pkg/strategy/drift/strategy.go
- pkg/types/indicator.go
- pkg/types/trade_stats.go
- pkg/util/pointer.go
- pkg/util/pointer_18.go
feature: smartcancel for drift
feature: rebalance on internal position
feature: dump config
feature: dump parameter to tg, esp series
fix: order tag, position calculation and bp/sp of drift
fix: empty internal position on start if there's already stored data in redis
> Drift rebase

- pkg/backtest/matching.go
- pkg/backtest/matching_test.go
- pkg/bbgo/exit.go
- pkg/bbgo/interact.go
- pkg/bbgo/persistence.go
- pkg/bbgo/persistence_test.go
- pkg/bbgo/reflect.go
- pkg/bbgo/trader.go
- pkg/dynamic/can.go
- pkg/strategy/drift/output.go
- pkg/strategy/output.go
- pkg/types/account.go
- pkg/types/market.go
also fix `exits` printing
re-implement `CanInt` which doesn't exist in go1.17
call TruncateQuantity on the SubmitOrders and new Trades in backtest
> feature: drift & print strategy config

- pkg/backtest/report.go
- pkg/cmd/backtest.go
Calculate realized Sharpe ratio and Sortino ratio in backtest for each symbols. This is a reference implementation for integrating `IntervalProfitCollector` into backtest.
> backtest: calculate realized Sharpe & Sortino ratios

- pkg/strategy/bollmaker/strategy.go
Fix the following nil pointer panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x4bb8187]
goroutine 1 [running]:
github.com/c9s/bbgo/pkg/bbgo.(*ExchangeSession).MarketDataStore(0x0, {0xc0004cbc9a, 0x6})
/Users/coldturnip/dev/rfns/bbgo/pkg/bbgo/session.go:492 +0x27
github.com/c9s/bbgo/pkg/strategy/bollmaker.(*DynamicSpreadSettings).Initialize(0xc000a43c78, {0xc0004cbc9a, 0x6}, 0x0?)
/Users/coldturnip/dev/rfns/bbgo/pkg/strategy/bollmaker/dynamic_spread.go:52 +0x11a
github.com/c9s/bbgo/pkg/strategy/bollmaker.(*Strategy).Run(0xc000a43b80, {0x555c7f0?, 0xc000111f80}, {0x401619a?, 0x0?}, 0xc0002d7040)
/Users/coldturnip/dev/rfns/bbgo/pkg/strategy/bollmaker/strategy.go:440 +0xfe …
```
> strategy: bollmaker: fix nil pointer

- config/bollmaker.yaml
- pkg/strategy/bollmaker/dynamic_spread.go
- pkg/strategy/bollmaker/strategy.go
Scale spread base on weighted Bollinger band width ratio between default and neutral bands.
The new scaling strategy is set under `dynamicSpread/weightedBollWidth`, and the original amplitude-based scaling is now `dynamicSpread/amplitude`.
Given the default band: moving average `bd_mid`, band from `bd_lower` to `bd_upper`.
And the neutral band: from `bn_lower` to `bn_upper`
Set the sigmoid weighting function:
- to ask spread, the weighting density function `d_weight(x)` is `sigmoid((x - bd_mid) / (bd_upper - bd_lower))`
- to bid spread, the weighting density function `d_weight(x)` is `sigmoid((bd_mid - x) / (bd_upper - bd_lower))`
Then calculate the weighted band width ratio by taking integral of `d_weight(x)` from `bx_lower` to `bx_upper`:
- `weighted_ratio = integral(d_weight from …
> strategy: bollmaker: dynamic spread by weighted Bollinger width ratio

- config/bollmaker.yaml
- pkg/strategy/bollmaker/dynamic_spread.go
While calculating BB width ratio, add configurable sensitivity factor to weighting function. The weighting density function becomes:
```
1                  x - default_BB_mid
sigmoid weighting function f(y) = ------------- where y = --------------------
1 + exp(-y)              w / sensitivity
```
The greater sensitivity factor, the sharper weighting function. This factor must be positive and default set to 1.0 .
> strategy: bollmaker: sensitivity factor of BB width ratio

- pkg/backtest/exchange.go
- pkg/backtest/exchange_klinec.go
- pkg/backtest/matching.go
- pkg/backtest/report.go
- pkg/cmd/backtest.go
- pkg/fixedpoint/convert.go
- pkg/fixedpoint/dec.go
- pkg/service/backtest.go
- pkg/strategy/output.go
- pkg/types/indicator.go
- pkg/types/sharpe.go
- pkg/types/sortino.go
- pkg/types/trade_stats.go
- fix taker price (not always use m.LastPrice on instant limit trade)
- reorder LastKLine assignment
- reorder interval emit order
- reorder matching engine processing to the beginning of all the kline close event
> fix: backtest

- examples/exchange-api/binance-margin/main.go
- pkg/backtest/exchange.go
- pkg/bbgo/exit_trailing_stop_test.go
- pkg/bbgo/interact.go
- pkg/bbgo/order_execution.go
- pkg/bbgo/order_executor_general.go
- pkg/cmd/orders.go
- pkg/datatype/floats/funcs_test.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/kucoin/exchange.go
- pkg/exchange/max/exchange.go
- pkg/exchange/okex/exchange.go
- pkg/grpc/server.go
- pkg/strategy/fmaker/strategy.go
- pkg/strategy/xgap/strategy.go
- pkg/types/exchange.go
- pkg/types/mocks/mock_exchange.go
all: simplify underlying exchange submitOrder method
- Replace SubmitOrders with SubmitOrder
- Accept only one submit order and return one created order
- Add bbgo.BatchPlaceOrders helper method and bbgo.BatchRetryPlaceOrders method
> refactor: simplify submit order

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
fixes #923 
when listenKey is expired, the private message will not be recieved anymore, hence we need to trigger the reconnect.
> fix: binance listenkey expired

- pkg/strategy/bollmaker/dynamic_spread.go
Sorry for making fixing patch again. Correct the settings fallback logic to avoid WeightedBollWidthRatioSpreadSettings getting overridden accidentally.
> bollmaker: fix settings overriding

- pkg/bbgo/risk.go
- pkg/bbgo/risk_test.go
- pkg/notifier/slacknotifier/slack.go
> bbgo: add price check and add max leverage for cross margin

- pkg/interact/telegram.go
- pkg/util/string.go
- pkg/util/string_test.go
- add rate limit in telegram.
- split messages by size limit and unicode header.
not strictly following the size limit (4096 bytes) and rate limit (100req/s) written in telegram api doc.  
use 3000, 10 instead.
> fix: add rate limit on telegram api and split messages by unicode

- pkg/strategy/supertrend/linreg.go
fix: supertrend-strategy: LinReg baseline slope wrongly calculated as reciprocal
> fix: supertrend-strategy: LinReg baseline slope wrongly calculated

- pkg/bbgo/order_executor_general.go
do not check for base balance for futures orders in reduceQuantityAndSubmitOrder()
> fix/general-order-executor: do not check for base balance for futures

- config/irr.yaml
- pkg/strategy/irr/draw.go
- pkg/strategy/irr/neg_return_rate.go
- pkg/strategy/irr/strategy.go
Due to the severe "delay" issue in binance 1s kline stream.
~~We've refactored irr strategy into backtesting mode (consume KLine onClose), and real-time mode (consume bookTicker which triggered every interval via goroutine)~~
~~Now we've redesigned the time ticker(goroutine) to consume aggerate trade market stream based on web socket .~~
Rollback to interval time trigger for a much easier programming model and really small intervals.
> strategy:irr: a mean reversion based on box of klines in same direction

- .gitattributes
- config/grid2-max.yaml
- config/grid2.yaml
- data/bbgo_test.sql
- data/bbgo_test.sqlite3
- doc/topics/strategy-testing.md
- pkg/bbgo/activeorderbook.go
- pkg/bbgo/activeorderbook_callbacks.go
- pkg/bbgo/trade_store.go
- pkg/strategy/grid2/grid.go
- pkg/strategy/grid2/profit.go
- pkg/strategy/grid2/strategy.go
- pkg/strategy/grid2/strategy_test.go
- pkg/types/kline.go
- pkg/types/position.go
> strategy: grid2 [part2] -- reverse order and arb profit calculation

- pkg/cmd/root.go
```
Failed to fire hook: failed to acquite target io.Writer: failed to open file &{log/access_log.%Y%m%d [%!s(*strftime.stdlibFormat=&{log/access_log.20060102})]}: open log/access_log.20221228: no such file or directory
```
> FIX: create log dir to avoid error

- pkg/strategy/grid2/strategy.go
- pkg/strategy/grid2/strategy_test.go
It is recommending to explicitly specify client order IDs to avoid retrying the same order but with different client order IDs. Let foreign exchange help ensure uniqueness of the same order.
> FIX: [grid2] specify client order id explicitly

- cmd/bbgo-lorca/main.go
- cmd/bbgo-webview/main.go
- pkg/bbgo/trader.go
- pkg/cmd/run.go
Always use persistence facade from the given context.
> FIX: add context to LoadState

- config/supertrend.yaml
`interval` only accepts string
The error from backtest
```
[0000] FATAL cannot execute command error=json: cannot unmarshal number into Go struct field HigherHighLowerLowStop.exits.higherHighLowerLowStopLoss.interval of type string
```
> FIX: supertrend config type error

- config/rsicross.yaml
- pkg/bbgo/order_executor_general.go
- pkg/bbgo/trader.go
- pkg/cmd/strategy/builtin.go
- pkg/dynamic/inject.go
- pkg/dynamic/inject_test.go
- pkg/strategy/common/strategy.go
- pkg/strategy/linregmaker/strategy.go
- pkg/strategy/rsicross/strategy.go
- pkg/strategy/scmaker/strategy.go
```
START TIME: Sat, 01 Jan 2022 08:00:00 CST
END TIME: Tue, 01 Feb 2022 08:00:00 CST
INITIAL TOTAL BALANCE: BalanceMap[BTC: 0, USDT: 10000]
FINAL TOTAL BALANCE: BalanceMap[BTC: 0.03956, USDT: -0.94693957]
binance BTCUSDT PROFIT AND LOSS REPORT
TRADES SINCE: 2022-01-01 00:09:59.999 +0000 UTC
NUMBER OF TRADES: 2567
POSITION BTCUSDT: average cost = 38438.09978741, base = 0.03956, quote = -3025.02864113
AVERAGE COST: $ 38,438.10
BASE ASSET POSITION: 0.03956
TOTAL BUY VOLUME: 111.46599
TOTAL SELL VOLUME: 111.42643
CURRENT PRICE: $ 38,500.98
CURRENCY FEES:
- USDT: 6973.6478243
PROFIT: $ 1,981.27
UNREALIZED PROFIT: $ 2.49
INITIAL ASSET IN USDT ~= 10000.00000 USDT (1 BTC = 46216.93) …
```
> FEATURE: add rsicross strategy

- README.md
- config/convert.yaml
- pkg/bbgo/activeorderbook.go
- pkg/bbgo/order_executor_general.go
- pkg/bbgo/order_executor_simple.go
- pkg/cmd/strategy/builtin.go
- pkg/strategy/convert/strategy.go
- pkg/types/market.go
- pkg/util/tradingutil/trades.go
This strategy is used for converting specific asset to another asset
> FEATURE: [strategy] Add convert strategy

- pkg/strategy/convert/strategy.go
- pkg/strategy/xalign/strategy.go
- pkg/types/market.go
- pkg/types/market_test.go
- pkg/util/tradingutil/trades_test.go
GreaterThanMinimalOrderQuantity uses the order side for the quantity truncation, and use the truncated quantity to validate the MOQ (minimal order quantity), which is more precise than just IsDustQuantity() since the quantity might have more decimal numbers outside of the precision that is supported by the exchange.
> REFACTOR: apply market.GreaterThanMinimalOrderQuantity on both convert and xalign

- migrations/mysql/20230815173104_add_bybit_klines.sql
- migrations/sqlite3/20230815173104_add_bybit_klines.sql
- pkg/migrations/mysql/20230815173104_add_bybit_klines.go
- pkg/migrations/sqlite3/20230815173104_add_bybit_klines.go
```
---
sessions:
bybit:
exchange: bybit
envVarPrefix: bybit
#max:
riskControls:
sessionBased:
max:
orderExecutor:
bySymbol:
BTCUSDT:
basic:
minQuoteBalance: 100.0
maxBaseAssetBalance: 3.0
minBaseAssetBalance: 0.0
maxOrderAmount: 1000.0
backtest:
startTime: "2023-05-09"
endTime: "2023-05-20"
symbols:
- BTCUSDT
sessions: [bybit]
accounts:
bybit:
balances:
BTC: 0.0
USDT: 10000.0
exchangeStrategies:
- on: bybit
grid:
symbol: BTCUSDT
quantity: 0.001
gridNumber: 30
profitSpread: 100.0  # The profit price spread that you want to add to your sell order when your buy order is executed
upperPrice: 28_000.0
lowerPrice: 25_000.0
```
```
go run ./cmd/bbgo backtest -v --sync --config config/grid.yaml
```
```
START TIME: Tue, 09 May 2023 …
```
> FEATURE: [bybit] add kline backtest

- pkg/exchange/bybit/bybitapi/get_open_orders_request.go
- pkg/exchange/bybit/bybitapi/types.go
- pkg/exchange/bybit/convert.go
- pkg/exchange/bybit/convert_test.go
- pkg/exchange/bybit/exchange.go
- pkg/exchange/bybit/stream.go
```
godotenv -f .env.local -- go run ./cmd/bbgo submit-order --session $BBGO_SESSION --symbol=BTCUSDT --side=buy --quantity=0.02 --market=true 
[0000]  INFO querying market info from bybit... session=bybit
[0000]  INFO querying account balances... session=bybit
[0000]  INFO account bybit balances: session=bybit
[0000]  INFO  DOT: 4.832517
[0000]  INFO  USDT: 30438.78659329 (locked 4.6)
[0000]  INFO  BTC: 4.36294865
[0000]  INFO submitted order: {ClientOrderID: Symbol:BTCUSDT Side:BUY Type:MARKET Quantity:0.02 Price:0 AveragePrice:0 StopPrice:0 Market:{Symbol:BTCUSDT LocalSymbol:BTCUSDT PricePrecision:-8 VolumePrecision:-6 QuoteCurrency:USDT BaseCurrency:BTC MinNotional:1 MinAmount:1 MinQuantity:0.000048 MaxQuantity:71.73956243 StepSize:0.000001 MinPrice:1 MaxPrice:2000000 TickSize:0.01} …
```
> FIX: [bybit] quantity in buy market order

- pkg/exchange/bybit/bybitapi/get_open_orders_request.go
- pkg/exchange/bybit/bybitapi/types.go
- pkg/exchange/bybit/convert.go
- pkg/exchange/bybit/convert_test.go
測試結果如下，包含 Market buy/sell, Limit buy/sell
```
stream_test.go:80: got update ORDER bybit | Aug 18 00:50:33.692 | UUID 1489439576071192320 (1489439576071192320) | BTCUSDT | MARKET BUY  | 0/0 @ 0 | NEW
stream_test.go:80: got update ORDER bybit | Aug 18 00:50:33.692 | UUID 1489439576071192320 (1489439576071192320) | BTCUSDT | MARKET BUY  | 0.008403/0.00840311 @ 0 | PARTIALLY_FILLED
stream_test.go:80: got update ORDER bybit | Aug 18 00:50:33.692 | UUID 1489439576071192320 (1489439576071192320) | BTCUSDT | MARKET BUY  | 0.008403/0.008403 @ 0 | FILLED
stream_test.go:80: got update ORDER bybit | Aug 18 00:50:46.386 | UUID 1489439682556087040 (1489439682556087040) | BTCUSDT | LIMIT BUY  | 0/0.01 @ 23800.6898 | NEW
stream_test.go:80: got update ORDER bybit | Aug 18 00:50:46.386 | UUID …
```
> FIX: [bybit] fix quantity unit from quote coin to base coin

- pkg/exchange/bybit/exchange.go
1. The previous implementation aimed to ensure that any time range is under control, but it seems that it did not achieve that. So i removed it.
```
if options.StartTime != nil && options.EndTime != nil && options.EndTime.Sub(*options.StartTime) > halfYearDuration {
return nil, fmt.Errorf("StartTime and EndTime cannot exceed 180 days, startTime: %v, endTime: %v, diff: %v",
options.StartTime.String(),
options.EndTime.String(),
options.EndTime.Sub(*options.StartTime)/24)
}
```
2. Modify the lastTradeId to 1 if it is currently 0. This adjustment will enable us to obtain additional data using the FromTradeId option. By specifying the FromTradeId, we can ensure that the query result is in ascending order.
> FIX: [bybit] fix bybit query trades

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/parse_test.go
- pkg/exchange/binance/stream.go
- pkg/strategy/xfunding/strategy.go
After listening for more than one hour, the event: ListenKeyExpired will be sent from binance server.
```text
ERROR websocket event parse error, message: {"e": "listenKeyExpired","E": "1695716647064","listenKey": "2rtkU3NxjtBFIw2zxhLMvTJ0jGsp87IZUDc4gY0F47aoF9pVvdxZUbozMog74fGU"} error=json: cannot unmarshal string into Go struct field ListenKeyExpired.E of type int64
```
To fix this elegantly, use json.Number to store timestamp.
> fix: listenKeyExpired event sends string timestamp

- config/fixedmaker.yaml
- pkg/strategy/common/strategy.go
- pkg/strategy/fixedmaker/strategy.go
- remove skew and atr multiplier from fixedmaker
- fix common.Strategy.IsHalted
- rename some variables
> REFACTOR: Make fixedmaker simpler

- pkg/exchange/max/maxapi/restapi.go
Try to reduce `read: connection reset by peer` issue, this may be caused by the unusable idle connection.
> CHORE: [maxapi] change default http transport settings

- pkg/exchange/binance/convert.go
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
- pkg/types/channel.go
- pkg/types/liquidation_info.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
Show the forced liquidation event from binance.
> feature: add forceOrder api for binance to show liquid info

- config/fixedmaker.yaml
- pkg/risk/riskcontrol/position.go
- pkg/strategy/common/strategy.go
- pkg/strategy/fixedmaker/strategy.go
cancel previous order before submitting position release order to prevent duplicate orders
> FIX: Fix duplicate orders caused by position risk control

- config/xfixedmaker.yaml
```
START TIME: Sun, 01 Jan 2023 08:00:00 CST
END TIME: Mon, 02 Jan 2023 08:00:00 CST
INITIAL TOTAL BALANCE: BalanceMap[USDT: 25000, BTC: 0.5]
FINAL TOTAL BALANCE: BalanceMap[USDT: 25073.18048103, BTC: 0.495]
max BTCUSDT PROFIT AND LOSS REPORT
TRADES SINCE: 2023-01-01 00:05:59.999 +0000 UTC
NUMBER OF TRADES: 171
POSITION BTCUSDT: average cost = 16589.208756, base = -0.005, quote = 83.71661545
AVERAGE COST: $ 16,589.21
BASE ASSET POSITION: -0.005
TOTAL BUY VOLUME: 0.425
TOTAL SELL VOLUME: 0.43
CURRENT PRICE: $ 16,612.66
CURRENCY FEES:
- USDT: 10.59896897
PROFIT: $ 2.57
UNREALIZED PROFIT: -$ 0.12
INITIAL ASSET IN USDT ~= 23261.325000 USDT (1 BTC = 16522.65)
FINAL ASSET IN USDT ~= …
```
> CHORE: update xfixedmaker config for backtest

- pkg/exchange/bitget/stream.go
- pkg/exchange/bitget/stream_callbacks.go
- pkg/exchange/bitget/stream_test.go
- pkg/exchange/bitget/types.go
https://bitgetlimited.github.io/apidoc/en/spot/#trades-channel
> FEATURE: [bitget]  support market trade stream

- pkg/indicator/rma.go
> MINOR: [indicator] remove zero padding from RMA

- pkg/exchange/bybit/convert.go
- pkg/exchange/bybit/convert_test.go
- pkg/exchange/kucoin/convert.go
The precision should be positive. Bybit is according to Kucoin, so it is also incorrect..
Other exchanges are correct.
bybit document: https://bybit-exchange.github.io/docs/v5/market/instrument
```
"basePrecision": "0.000001",
"quotePrecision": "0.00000001",
```
kucoin document: https://www.kucoin.com/docs/rest/spot-trading/market-data/get-symbols-list
```
"quoteIncrement": "0.000001",
"priceIncrement": "0.000001",
```
> FIX: [bybit][kucoin] fix negative volume, price precision

- doc/development/adding-new-exchange.md
- doc/development/release-process.md
- doc/development/series.md
This pull request fixes typos in documentation of directory `doc/development`. I kindly request the repository maintainers to review and merge it. Thanks! :heart:
> docs: fix typos in doc/development

- pkg/exchange/bitget/bitgetapi/get_symbols_request.go
- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
The `PriceScale`, `QuantityScale` are string type, not int.
> REFACTOR: [bitget] get symbol api

- pkg/service/trade.go
1. In order to query trades from db page by page, I add `Until` options so we can query trades from db page by page. Note that `Until` is exclusive.
2. The `symbol` clause will be added only if it's not an empty string. I think it should not affect existing behavior. Please review that thanks.
> FEATURE: query trades from db page by page

- pkg/exchange/bitget/stream.go
- pkg/exchange/bitget/stream_callbacks.go
- pkg/exchange/bitget/stream_test.go
- pkg/exchange/bitget/types.go
- pkg/exchange/bitget/types_test.go
https://bitgetlimited.github.io/apidoc/en/spot/#candlesticks-channel
The closed flag of Kline is not supported by Bitget. Therefore, we store the last Kline to compare the time duration and determine whether the Kline is closed.
> FEATURE: [bitget] support kline subscription on stream

- pkg/exchange/bybit/market_info_poller.go
- pkg/exchange/bybit/market_info_poller_test.go
- pkg/exchange/bybit/stream.go
- pkg/exchange/bybit/stream_test.go
To periodically fetch the fee rate.
The `feeRatePoller.getAllFeeRates` are copied from `stream.getAllFeeRates`
> FEATURE: [bybit] to periodically fetch the fee rate

- pkg/exchange/bybit/market_info_poller.go
- pkg/exchange/bybit/market_info_poller_test.go
- pkg/exchange/bybit/stream.go
1. Remove the retry func and we can rely on the ticker instead.
2. Add fee rate recover.
REMARK:
The default rate for takers/markets on Bybit SPOT is 0.1%
https://www.bybit.com/en-US/help-center/article/Trading-Fee-Structure
> FIX: [bybit] rm retry and add fee recover

- pkg/bbgo/session.go
- pkg/exchange/bitget/bitgetapi/v2/get_history_orders_request.go
- pkg/exchange/bitget/bitgetapi/v2/get_history_orders_request_test.go
- pkg/exchange/bitget/bitgetapi/v2/get_trade_fills.go
- pkg/exchange/bitget/bitgetapi/v2/get_unfilled_orders_request.go
- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
- pkg/exchange/bitget/stream.go
- pkg/exchange/bitget/stream_callbacks.go
- pkg/exchange/bitget/stream_test.go
- pkg/exchange/bitget/types.go
- pkg/types/stream.go
https://www.bitget.com/api-doc/spot/websocket/private/Order-Channel
```
//stream_test.go:153: order update ORDER bitget | UUID 1107940456212631553 (1107940456212631553) | BGBUSDT | MARKET SELL | 0/285 @ 0 | NEW | Nov 13 12:45:09.976 -> Nov 13 12:45:09.976
//stream_test.go:153: order update ORDER bitget | UUID 1107940456212631553 (1107940456212631553) | BGBUSDT | MARKET SELL | 22.5835/285 @ 0.48706 | PARTIALLY_FILLED | Nov 13 12:45:09.976 -> Nov 13 12:45:10.006
//stream_test.go:153: order update ORDER bitget | UUID 1107940456212631553 (1107940456212631553) | BGBUSDT | MARKET SELL | 45.1675/285 @ 0.48706 | PARTIALLY_FILLED | Nov 13 12:45:09.976 -> Nov 13 12:45:10.007
//stream_test.go:153: order update ORDER bitget | UUID 1107940456212631553 (1107940456212631553) | BGBUSDT | MARKET SELL | …
```
> FEATURE: [bitget] implement order, trade user stream

- cmd/bbgo-webview/main.go
- pkg/bbgo/trader.go
- pkg/cmd/run.go
The new generation of strategies introduces the use of `common.Strategy`, which is embedded as a struct to simplify the strategy implementation. This approach reduces the amount of code required for writing strategies. During the transition from YAML configuration to runtime instance, whenever any configuration field of `common.Strategy` is set, it initializes the `common.Strategy` structure to enable persistence. In other words, `s.Strategy == &common.Strategy` is established by the JSON unmarshal process. Conversely, if it's not set, `s.Strategy` becomes `nil`, preventing persistence from being loaded.
Inside the `Run()` function, we directly assign `s.Strategy = &common.Strategy{}`. This overwrites the object that was previously loaded from persistence, causing the strategy to start …
> FIX: move Initialize() call out, call it before the LoadState

- README.md
Resolve #1369 
Fixed some grammatical errors.
> DOC: Fix grammatical errors

- pkg/strategy/xdepthmaker/strategy.go
Remove the shared trade collector and order store, simplify the code also fix some race conditions
> FIX: [xdepthmaker] remove shared trade collector and fix hedge

- pkg/strategy/rebalance/multi_market_strategy.go
- pkg/strategy/rebalance/strategy.go
- fix position map and profit stats map
- graceful cancel orders to avoid `Cannot lock funds` error
- rebalance on order filled
> FIX: [rebalance] fix position map and profit stats map

- doc/build-from-source.md
`frontend` got moved to `apps/frontend` in this [commit](https://github.com/c9s/bbgo/commit/46d8d28b)
> DOCS: fix frontend path

- pkg/exchange/okex/stream.go
- pkg/types/stream.go
The okx supports the low-level ping pong event, but it only supports less than 30 seconds. Therefore, I added a new function for setPingInterval.
> FEATURE: [okx] set ping interval

- pkg/bbgo/interact.go
Executing the Telegram command /position to request information about open positions results in an error message when there are no open positions. The state of having no open positions should not be treated as an error.
> FIX: [telegram] prevent sending error to telegram for the case of no opened position

- pkg/exchange/okex/convert.go
- pkg/exchange/okex/convert_test.go
- pkg/exchange/okex/exchange.go
In the past, I used the bill ID as the trade ID because OKX only supports querying trades by [bill ID](https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-transaction-details-last-3-months). However, the bill ID is not supported on websocket events.
I updated the implementation, handling the bill ID as a filter in the loop instead of getting the ID from outside, even if you use batch.query.
> FIX: [okx] fix trade id

- pkg/exchange/okex/exchange.go
```
request failed with status code: 429, body: "{\"msg\":\"Too Many Requests\",\"code\":\"50011\"
```
In the past, I allowed a maximum of N buckets in the rate limiter, but OKX seems to have a strict restriction, leading to issues with the rate limiter. Therefore, I have now updated the value to 1.
> FIX: [okx] refine okx rate limiter

- pkg/indicator/v2/smma.go
- pkg/indicator/v2/smma_test.go
* Add the smma indicator in v2 indicators
* Add a test
> FEAT: Add SMMA indicator

- pkg/bbgo/activeorderbook.go
If errors occur in CancelOrders and QueryOpenOrders, it will result in an infinite loop because the orders have been replaced with an empty slice.
> FIX: [ActiveOrderBook] use origin order if error occurred

- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
2023/11/05 The market order will be executed immediately, so this check is used to handle corner cases.
2024/03/06 After placing a Market Order, we can retrieve it through the unfilledOrder API, so we still need to
handle the Market Order status.
> FIX: [bitget] support market order on bitget unfilled order conversion

- pkg/bbgo/order_executor_general.go
This PR adds the ability to close short positions with the ClosePosition method. It adjusts the order quantity based on the available quote balance and the current ask price for the symbol.
> FEATURE: close short positions with ClosePosition

- pkg/bbgo/environment.go
- pkg/exchange/binance/exchange.go
- pkg/service/sync.go
1. Enable Paper trading in sync command
2. Refactor pkg/util
3. take advantage of adshao/go-binance/v2 in order to set URL for paper trading
* Sync for Binance paper trading works now
```
❯ ./bbgo sync
[0000]  INFO syncing symbols [ETHUSDT] from session binance
[0000]  INFO syncing binance ETHUSDT trades from 2024-01-01 00:00:00 +0000 UTC...
[0000]  INFO inserting types.Trade: TRADE binance ETHUSDT  BUY 0.05 @ 3563.64 | AMOUNT 178.182 | FEE 0 ETH | OrderID 1923248 | TID 519244 | Mar 21 16:17:00.022
[0000]  INFO inserting types.Trade: TRADE binance ETHUSDT  BUY 0.05 @ 3562.79 | AMOUNT 178.1395 | FEE 0 ETH | OrderID 1924216 | TID 519503 | Mar 21 16:21:30.874
[0000]  INFO inserting types.Trade: TRADE binance ETHUSDT  BUY 0.029 @ 3535.23 | AMOUNT 102.52167 | FEE 0 ETH | OrderID 1928686 | TID …
```
> support Binance paper trading for sync sub-command

- migrations/mysql/20240531163411_trades_created.sql
- migrations/sqlite3/20240531163411_trades_created.sql
- pkg/types/trade.go
A trade may be missed initially and fetched after it has occurred, so we add inserted_at column.
> MINOR: add inserted_at column to trades

- pkg/service/trade.go
- pkg/service/trade_test.go
Now user is able to specify the ordering column.
> REFACTOR: support custom order by column

- pkg/core/tradecollector.go
- pkg/exchange/max/convert.go
- pkg/exchange/max/exchange.go
- pkg/exchange/max/maxapi/account.go
- pkg/strategy/xdepthmaker/strategy.go
support hedge with a different symbol
fix MAX's withdraw data convertion (v3 api does not provide the status field)
> FEATURE: [xdepthmaker] separate hedge symbol

- pkg/types/series_float64.go
- pkg/types/series_float64_test.go
```
series := types.NewFloat64Series()
series.PushAndEmit(2)
series.PushAndEmit(4)
series.PushAndEmit(6)
series.PushAndEmit(8)
series.PushAndEmit(10)
t.Log(series.SeriesBase.Length())
t.Log(series.Mean(3))
t.Log(series.Stdev(3))
}
```
The result is zero.
> fix float64 series use mean or stdev function result is zero

- pkg/types/order.go
new side effect AUTO_BORROW_REPAY, document here: https://www.binance.com/en/support/faq/how-to-use-the-sideeffecttype-parameter-with-the-margin-order-endpoints-f9fc51cda1984bf08b95e0d96c4570bc
> FEATURE: [binance] add new margin order side effect AUTO_BORROW_REPAY

- pkg/exchange/binance/exchange.go
update binance margin order to support IOC and FOK, same behavior with spot order
> FIX: update timeInForce for binance margin order

- pkg/strategy/bollgrid/strategy.go
fix bad syntax for struct tag value
In fact, the previous json tag cannot be parsed correctly
> FIX: fix shutdownCancelProfitOrders json tag

- doc/topics/rw-strategy.md
DOC: add documentation on how to print/edit fields from a strategy in interactive scenarios (ex: telegram or slack)
> doc: add the explanation on how to read/write strategy fields

- pkg/bbgo/activeorderbook.go
For some special case like IOC order is filled immediately, current code caused OnFilled event is called before OnNew event.
In order to fix it, I update the position of b.EmitNew(order) to guarantee OnNew event is always called before OnFilled event.
> FIX: fix OnNew event must be called before OnFilled

- pkg/strategy/common/strategy.go
Strategy.RiskController.circuitBreakRiskControl now uses the new circuitbreaker: circuitbreaker.BasicCircuitBreaker
> Use new circuitbreaker in common strategy

- pkg/exchange/bybit/bybitapi/client_test.go
- pkg/exchange/bybit/bybitapi/get_execution_list_request.go
- pkg/exchange/bybit/bybitapi/get_execution_list_request_requestgen.go
- pkg/exchange/bybit/convert.go
- pkg/exchange/bybit/exchange.go
The UTA account will return the fee currency, so just use that parameter instead of calculating it yourself.
> FEATURE: [bybit] use fee currency of trade

- pkg/bbgo/session.go
- pkg/server/routes.go
this field is not used and it increase the memory usage
> FIX: [core] remove session order store

- pkg/strategy/xdepthmaker/strategy_test.go
- pkg/testing/testhelper/pricevolumeslice.go
- pkg/types/price_volume_slice.go
thanks to @DaniilSokolyuk, this should fix #1861
see https://github.com/c9s/bbgo/issues/1861
> FIX: fix AverageDepthPrice and add test TestPriceVolumeSlice_AverageDepthPrice

- config/sentinel.yaml
- go.mod
- go.sum
- pkg/cmd/strategy/builtin.go
- pkg/datatype/floats/slice.go
- pkg/strategy/sentinel/strategy.go
This pull request introduces a new trading strategy named "Sentinel" and includes various changes to support its implementation. The most important changes include the addition of the configuration for the Sentinel strategy, updates to dependencies, and the implementation of the strategy itself.
* [`config/sentinel.yaml`](diffhunk://#diff-567a2873282a19afd4453422fa4ba2e0dcd8ff8a185d784e9570f5fb6e01f3f4R1-R19): Added configuration for sessions, persistence, and exchange strategies, including settings for the Sentinel strategy.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R128): Added `github.com/narumiruna/go-iforest` as an indirect dependency.
* [`pkg/cmd/strategy/builtin.go`](diffhunk://#diff-4b4599b9a4be6b33da6400a2f3ea0d0942210bb05a3cd23e …
> STRATEGY: Detect abnormal volume increases using isolation forest

- config/sentinel.yaml
- pkg/strategy/sentinel/strategy.go
- Batch query historical Kline data at the start.
> FEATURE: [sentinel] query historical kline data

- go.mod
- go.sum
- pkg/ensemble/iforest/forest.go
- pkg/ensemble/iforest/forest_test.go
- pkg/ensemble/iforest/matrix.go
- pkg/ensemble/iforest/matrix_test.go
- pkg/ensemble/iforest/path.go
- pkg/ensemble/iforest/quantile.go
- pkg/ensemble/iforest/quantile_test.go
- pkg/ensemble/iforest/tree.go
- pkg/strategy/sentinel/strategy.go
https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/icdm08b.pdf
> FEATURE: add isolation forest algorithm

- pkg/exchange/binance/binanceapi/futures_get_position_risks_request.go
Update the attribute `MarginAsset` of `FuturesPositionRisk` to a string type.
> [FIX]: fix positionRisk attribute type

- config/sentinel.yaml
- pkg/ensemble/iforest/forest.go
- pkg/strategy/sentinel/strategy.go
This pull request includes significant changes to the anomaly detection strategy and configuration. The most important changes involve updating the configuration settings, modifying the detection logic, and improving the handling of historical data and notifications.
* [`config/sentinel.yaml`](diffhunk://#diff-567a2873282a19afd4453422fa4ba2e0dcd8ff8a185d784e9570f5fb6e01f3f4L7-R71): Removed the persistence settings and added multiple new exchange strategies with consistent parameters for different symbols.
* [`pkg/ensemble/iforest/forest.go`](diffhunk://#diff-466ab01444e19152fb40d9194518830f7d552f03d7a7b3c65b9934bed358affcL13-L27): Removed the `DetectionType` and related logic, simplified the threshold handling, and updated the `Options` struct. …
> FIX: [sentinel] Modify detection logic

- pkg/cmd/hoptimize.go
signal channel should not be used elsewhere. Reported by go vet.
refer: https://github.com/golang/go/issue/45043
> fix: misuse of unbuffered os.Signal channel as argument to signal.Notify

- pkg/exchange/bybit/exchange.go
When placing IOC order, we are not able to get order from order history api immediately. We should raise a special error to client.
> minor: [bybit] refine order histories error msg

- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/exchange_test.go
We should always use user specified client order id.
> fix: [binance] remove client order id prefix

- pkg/exchange/okex/exchange.go
In previous version, we always sent order id since the pointer will never be nil.
> fix: [okx] pass client order id

- pkg/bbgo/session.go
- pkg/util/string.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: using slices.Contains to simplify the code

- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/exchage.go
- pkg/exchange/coinbase/exchange_test.go
> FIX: [exchange] fix bugs and add integration tests for Coinbase Exchange

- pkg/exchange/coinbase/stream.go
Implement `OnConnect` and websocket auth.
Reference implementation (Python):
https://github.com/coinbase-samples/exchange-scripts-py/blob/main/websocket/auth_ws_channel.py
> FEATURE: [exchange] Coinbase Websocket connection

- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/exchage.go
Add missing fields for `types.Market`:
- `MinAmount` -> filled with `min_market_funds`
- `TickSize` -> filled with `quote_increment`
- `StepSize` -> filled with `base_increment`
- `MinPrice` -> optional, filled with `0`
- `MaxPrice` -> optional, filled with `0`
- `MinQuantity` -> derived by ticker price and `min_market_funds`
- `MaxQuantity` -> optional, filled with dummy value
> FIX: [exchange] add missing market info fields for Coinbase Exchange

- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/exchage.go
- pkg/exchange/coinbase/exchange_test.go
Fix timeout issue for QueryMarkets.
Fill dummy values for min/max quantity because:
1. Coinbase does not appose quantity limit on orders (but min notional)
2. there are other helper functions in bbgo which can adjust the order size to meet the min notional.
> FIX: [exchange] [coinbase] fill in dummy values for min/max quantity

- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/exchage.go
1. According to the doc of websocket feed of Coinbase, the `Hold` field is the `Locked` field
- See: https://docs.cdp.coinbase.com/exchange/docs/websocket-channels#balance-channel
2. Fix bug: there may be multiple trading accounts for one user, should use `.Add` method to accumulate the balance.
> FIX: [exchange] (coinbase) fix balance update

- pkg/exchange/coinbase/api/v1/create_order_request.go
- pkg/exchange/coinbase/api/v1/create_order_request_requestgen.go
- pkg/exchange/coinbase/exchage.go
- bug fix
- `size` is not required for all order
- use `price * quantity` as `funds`, which is required parameter for market order on Coinbase Exchange.
- update stop-limit order logic: using stop order on Coinbase Exchange. 
- as a result, we only support long position on stop-limit order.
> FIX: [coinbase] submit order logic

- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_handlers.go
- pkg/exchange/coinbase/stream_messages.go
- pkg/exchange/coinbase/stream_test.go
In this PR:
1. Implement handlers to bridge Coinbase events to standard events
2. Modify on-connection handler: publish balance snapshot event on connection.
> FEAT: [coinbase] implement stream message handlers

- pkg/exchange/coinbase/api/v1/constants.go
- pkg/exchange/coinbase/api/v1/get_orders_request.go
- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/parse.go
- pkg/exchange/coinbase/parse_test.go
- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_callbacks.go
- pkg/exchange/coinbase/stream_messages.go
The purpose of this PR is to:
1. minor refactoring, moving type conversion logics from api modules to application module
2. renaming `ActiveMessage` as `ActivateMessage` to be aligned with Coinbase documentation.
These are preliminary works for the upcoming PR #1928.
> FIX: [coinbase] fix stream handlers and order placing logics

- .vscode/settings.json
- pkg/exchange/coinbase/convert.go
- pkg/exchange/coinbase/exchage.go
- pkg/exchange/coinbase/parse.go
- pkg/exchange/coinbase/parse_test.go
- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_callbacks.go
- pkg/exchange/coinbase/stream_handlers.go
- pkg/exchange/coinbase/stream_messages.go
- pkg/exchange/coinbase/stream_test.go
1. update `.SubmitOrder` logic, to simplify the streaming handlers logic
- Do not support `limit order with funds`
- Only support stop limit order (via `stop` order on Coinbase Exchange) at long position .
2. By `1.`, update order-related event handlers accordingly.
> FIX: [coinbase] refactoring and fix order-related streaming event handling

- pkg/service/sync_task.go
The query on existing trade records from the DB was based on trade id and limit.
Whereas, the query via the exchange API is based on timestamp and trade id.
The inconsistency on the query conditions may cause error on corner cases.
There are chances the ids map may fail to filter out existing trade records and resulting in duplicate key error while inserting.
In this PR, I add an extra query for the record with the last trade id.
And I update the ids map accordingly so that self-trade records on both side will be included.
> FIX: [sync service] inconsistency of the query conditions on existing trades

- pkg/exchange/coinbase/stream_handlers.go
Skip `last_match` event.
Though it may miss trades from the last disconnection, it can prevent duplicate insert to the DB.
> FIX: [coinbase] skip last match event to prevent potential duplicate trades

- pkg/exchange/okex/exchange.go
- pkg/exchange/okex/exchange_test.go
由於使用before id 的 pagination 從 desc 變為 asc，先前可利用最後一個 id 直接撈取更大的資料，現在卻需要 N-1 次才能完成，效率大幅降低，且會包含重複的，和先前測試的結果不符。
現在改成使用 After，可直接利用最後一個 id 繼續撈曲剩下的資料回來，而且不會重複
> FIX: [okx] fix the before id bug

- pkg/strategy/grid2/grid.go
- pkg/strategy/grid2/grid_test.go
- pkg/strategy/xgap/strategy.go
- pkg/strategy/xgap/strategy_test.go
- pkg/util/round_precision.go
- pkg/util/round_precision_test.go
- refactor: move and export `roundAndTruncatePrice` in `grid` strategy
- round and truncate price for `xgap`
> FIX: [xgap] adjust mid price (round and truncate by price precision)

- pkg/exchange/okex/exchange.go
- pkg/exchange/okex/okexapi/client.go
Ref: https://www.okx.com/docs-v5/en/#overview-account-mode
> FIX: [okex] Correct RestBaseURL by removing trailing slash and add logging for client creation

- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_handlers.go
Revise the logic of handlers for user/market data stream
- A user data stream will by default subscribe to `user` channel and receive user order related events
- Implement `PrivateChannelSymbolSetter` for a user data stream
- The symbols to be subscribed for a user data stream is controlled by `privateChannelSymbols`.
- Only query account balances for a user data stream
> REFACTOR: [coinbase] Revise User/Market data stream connection logic

- pkg/bbgo/serialmarketdatastore.go
The market data stream may subscribe to multiple symbols at once.
Hence, we should filter on the trade feeds before we update the  data store.
> FIX: [SerialMarketDataStore] Add symbol check in handleMarketTrade to ensure correct trade processing

- pkg/exchange/coinbase/stream_handlers.go
- pkg/exchange/coinbase/stream_test.go
In this PR, I refactor the `handleConnect` method of the coinbase `Stream` object as following:
1. wrapping connection logics of user and market data stream into two separate methods:
- `buildMapForUserDataStream`
- `buildMapForMarketStream`
2. `writeSubscribeJson`: method that write the subscription JSON to the websocket connection
3. Instead of just logging on subscription error, use `panic` to abort the process
- the rationale is that we should prevent the process running since user/market data streams are important data feeds for the trading strategies. If there is any error on subscriptions, the stream is compromised and should be explicitly stopped instead of just logging a message.
> REFACTOR: (coinbase) wrapping connection logics into methods for better maintainability.

- config/binance-futures.yaml
- config/binance-margin.yaml
- pkg/bbgo/session.go
- pkg/cmd/userdatastream.go
- pkg/exchange/binance/binanceapi/client.go
- pkg/exchange/binance/binanceapi/client_test.go
- pkg/exchange/binance/binanceapi/util.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/futures.go
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
- pkg/exchange/factory.go
- pkg/types/stream.go
- pkg/util/ed25519.go
`listenKey` is deprecated:
https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG#user-data-streams
> FIX: [binance] apply new ws endpoint and use ed25519 authentication for spot trading

- pkg/bbgo/exit_hh_ll_stop.go
- pkg/exchange/bitget/stream.go
- pkg/exchange/bybit/stream.go
- pkg/migrations/mysql/migration_api.go
- pkg/migrations/sqlite3/migration_api.go
- pkg/optimizer/hpoptimizer.go
- pkg/strategy/drift/draw.go
- pkg/strategy/elliottwave/draw.go
- pkg/types/kline.go
- pkg/util/string.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max/min to simplify the code

- pkg/analysis/hawkes.go
- pkg/analysis/hawkes_test.go
add hawkes process on mark_function. if mark_function always returns 1, it means the intensity is for the occurrence of trades(or maybe order? depends on the meaning of historical data).
> feature: add Marked Hawkes Process implementation

- pkg/service/order.go
- pkg/service/trade.go
Add logging when exchange does not implement `ExchangeTradeHistoryService`
> FIX: [sync] Add logging for order and trade sync failures

- pkg/backtest/priceorder.go
- pkg/exchange/binance/binanceapi/client.go
- pkg/exchange/bitget/bitgetapi/client.go
- pkg/exchange/bybit/bybitapi/client.go
- pkg/exchange/kucoin/kucoinapi/client.go
fix inconsistent function name in comment
> chore: fix inconsistent function name in comment

- go.mod
- go.sum
- pkg/cmd/root.go
The ```rotatelogs.WithLinkName``` option in file-rotatelogs is not container-friendly.
> FEATURE: [log] replace the log rotation plugin with lumberjack

- pkg/exchange/max/exchange.go
- pkg/exchange/max/exchange_test.go
- pkg/strategy/xmaker/strategy.go
- pkg/types/error.go
- introduce RecoverOrderError to handle the recover error case
- use rate limiter to control the log level
- extend price update alert to 2min
> IMPROVE: [xmaker] add more improvements for order recovery
