- pkg/util/retry.go
> fix misspell

- config/bbgo.yaml
- config/buyandhold.yaml
otherwise would occur error
```
panic: backtest.endTime must be defined
```
> fix: backtest endTime

- pkg/service/trade.go
- pkg/service/trade_test.go
hi, I think it's worth testing the SQL generation code. In order to do that, I extract the trading SQL generation logic into separated functions and test them.
> minor: extract SQL generator function of trades table

- pkg/service/order.go
- pkg/service/order_test.go
> minor: extract query order sql generator

- README.md
- frontend/components/ConfigureDatabaseForm.js
- pkg/cmd/root.go
- pkg/cmd/run.go
- pkg/server/routes.go
- pkg/service/order.go
- pkg/service/trade.go
- pkg/service/trade_test.go
> add sqlite3 driver option to the wizard user interface

- pkg/backtest/exchange.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/ticker_test.go
- pkg/exchange/max/exchange.go
- pkg/exchange/max/ticker_test.go
- pkg/types/exchange.go
- pkg/types/ticker.go
PR that covers part of issue #100﻿
(Adding support for ticker API here. Another PR for asset calculation)
> feat: ticker API for exchanges

- README.md
- pkg/exchange/ftx/balance.go
- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/responses.go
- pkg/exchange/ftx/rest.go
- pkg/exchange/ftx/rest_test.go
- pkg/exchange/max/maxapi/restapi.go
- pkg/types/exchange.go
- pkg/util/http_response.go
- pkg/util/http_response_test.go
ticket: #109
Hello @c9s , I have implemented the `QueryAccountBalances` of FTX exchange, and also extracted some helpers. I have a question about currency conversion (that's why I add a TODO in the comment). I wonder know is there any global currencies string list? I don't know how to convert the FTX currency into the global currencies. If there's a list, I can define a string map in the `convert.go` and do the conversion. Thanks for your reply.
> feature: query FTX balances

- go.sum
- pkg/cmd/balances.go
- pkg/cmd/root.go
- pkg/exchange/ftx/exchange.go
Sometimes the document isn't that clear, so it will be better to have a command to test the function. I add a cmd to print your balance of this account. In the future I will add websocket related commands.
> feature: balance testing cmd

- pkg/cmd/balances.go
- pkg/cmd/orderbook.go
- pkg/cmd/utils.go
- pkg/exchange/ftx/stream.go
- pkg/exchange/ftx/stream_message_handler.go
- pkg/exchange/ftx/websocket.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
- pkg/service/websocket.go
It's ready to send a subscription to FTX websocket server, and I've printed the subscribed message successfully. Later I will implement the orderbook snapshot first.
> feature: print ftx websocket subscribed message

- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
Unmarshal all fields at the same time rather than one by one.
> minor: unmarshal all fields at the same time

- pkg/cmd/orderbook.go
- pkg/exchange/ftx/orderbook_update.json
- pkg/exchange/ftx/stream.go
- pkg/exchange/ftx/stream_message_handler.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
- pkg/types/orderbook.go
> feature: emit orderbook update 

- pkg/cmd/orders.go
- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/convert_test.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/rest_order_request.go
- pkg/exchange/ftx/rest_responses.go
Now we support limit/market orders on FTX. Note that I've only tested limit order.
> feature: place FTX order

- pkg/cmd/balances.go
apply environment to load sessions
> improve: improve balances command

- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
> fix: new rest client everytime

- linode/max-grid-usdttwd.sh
> feature: add linode stackscripts

- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/rest_order_request.go
- pkg/exchange/ftx/rest_responses.go
I follow the API document to implement this feature but haven't tested yet.
> feature: cancel FTX orders

- pkg/bbgo/active_book.go
- pkg/exchange/batch/batch.go
- pkg/exchange/max/maxapi/order.go
- pkg/fixedpoint/convert.go
- pkg/fixedpoint/convert_test.go
- pkg/strategy/grid/strategy.go
- fix the grid price calculation
- add persistence support
- fix reward sync bug
- add fixedpoint string parser
> feature: add grid state persistence support and few minor fixes

- pkg/cmd/orders.go
Fix how I initialized exchange.
> fix: fix placeorder cmd

- pkg/fixedpoint/convert.go
- pkg/fixedpoint/convert_test.go
I will use the util to calculate the price/volume precision for market.
> feature: get num of fractional parts

- pkg/cmd/market.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/rest.go
- pkg/exchange/ftx/rest_market_request.go
- pkg/exchange/ftx/rest_responses.go
Some fields are not supported by FTX, so I assign the zero value to them. Please help me verify each field carefully, thanks.
> feature: support query FTX markets

- pkg/cmd/orderbook.go
- pkg/exchange/ftx/stream.go
- pkg/exchange/ftx/stream_message_handler.go
- pkg/exchange/ftx/websocket.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/exchange/ftx/websocket_messages_test.go
- pkg/types/exchange.go
If you don't invoke `SetPublicOnly`,  I will login when connecting. Note that I haven't subscribe orders and trades yet, so the `orderupdate` command doesn't work yet.
> feature: authenticate ftx websocket

- pkg/exchange/ftx/convert.go
- pkg/exchange/ftx/convert_test.go
- pkg/exchange/ftx/exchange.go
- pkg/exchange/ftx/exchange_test.go
- pkg/exchange/ftx/rest_market_request.go
- pkg/exchange/ftx/rest_responses.go
FTX only supports REST Kline api
> ftx: query kline using rest api

- pkg/bbgo/trader.go
- pkg/strategy/bollgrid/strategy.go
- pkg/strategy/grid/strategy.go
- pkg/strategy/support/strategy.go
The PR adds a `Validator` interface for validating the given parameters in the YAML configuration. And I also moved some code from `Run()` method to `Validate()`.
Resolve #161
> Add validation interface to strategy

- pkg/notifier/telegramnotifier/interaction.go
This patch allows telegram bot to send message to a telegram group, to aggregate all notification in 1 place
> feat: allow telegram bot send to group

- pkg/exchange/max/maxapi/order.go
https://github.com/c9s/bbgo/issues/194
> feature: add ioc order type support to max exchange

- pkg/exchange/max/convert.go
- pkg/exchange/max/exchange.go
Changes
- Fix IOC order type for max exchange
> fix: add ioc trade type to order type

- pkg/strategy/bollgrid/strategy.go
我最近在用 bollgrid 時，發現偶爾在執行 `submitReverseOrder` 時會餘額不足，追查之後才發現是因為有一小部分被手續費扣掉了。譬如說我原本的 activeOrder 是買進 100 個 BTC，買到之後會馬上執行 `submitReverseOrder` 把這 100 個 BTC 以更高的價位賣出。但因為手續費的關係，這時我可能只剩 99.99999 個 BTC，就不會成功掛單。
為了避免這種情況，我在送出訂單之前會先檢查現在的餘額，如果我原本想送出掛單賣 100 個 BTC，但我只剩 99.99999 個，那我就只掛 99.99999 的賣單。
> 另外，因為我現在只有改 bollgrid 策略，如果覺得 grid 也需要的話我可以順便把它加進去～
> Check balance before submit reverse order

- pkg/strategy/bollgrid/strategy.go
In bollgrid strategy, The original behavior is that bbgo will stop generating new orders when the balance is insufficient.
Although the left balance is not much, I think it's wasteful to be idle there. Therefore, I use the remaining balance to send the last order when the balance is insufficient. I hope this will increase the utilization of assets.
> bollgrid: generate the last order if balance is not enough

- frontend/api/bbgo.js
- go.mod
- go.sum
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
Am I doing right ?
It's still work in progress. This PR is only for temporary review.
> [Binance future api] MarkPriceUpdateEvent

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
add market data stream "Continuous Contract Kline/Candlestick Streams"
> [Binance future api] ContinuousKlineEvent

- README.md
> Update README.md for mysql dsn

- pkg/cmd/backtest.go
> add force parameter for backtest

- pkg/bbgo/environment.go
try to fix #261 with given default config for notifications.
>  fix #261 provide default config for notification setting

- doc/build-from-source.md
Based on the instructions on the go website
> Add go installation instructions

- pkg/exchange/ftx/stream.go
Fire onKline also when onKlineClosed
> finetune ftx for #318

- README.md
- migrations/mysql/20211205162043_add_is_futures_column.sql
- migrations/sqlite3/20211205162302_add_is_futures_column.sql
- pkg/service/order.go
- pkg/service/trade.go
- pkg/types/order.go
- pkg/types/trade.go
cherry pick some commits from #299
> feature: integrate binance future types

- pkg/types/order.go
> order: add is_futures field for #344

- pkg/service/totp.go
> 	telegram: find USERNAME when USER env not found for windows.

- README.md
- migrations/mysql/20211211103657_update_fee_currency_length.sql
- migrations/sqlite3/20211211103657_update_fee_currency_length.sql
- pkg/migrations/mysql/20211211103657_update_fee_currency_length.go
- pkg/migrations/sqlite3/20211211103657_update_fee_currency_length.go
> db: 343 fee currency length 

- pkg/types/account.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
2st part of #333 to support binance futures.
```
modified:   pkg/types/account.go
modified:   pkg/types/standardstream_callbacks.go
modified:   pkg/types/stream.go
```
> types: add PositionMap in std Stream & callbacks

- pkg/exchange/ftx/stream.go
Last time i only handle the event in the begining, it only works in the first interval. this one fix them all.
> ftx: update kline event handling for #318

- config/pricealert-tg.yaml
- doc/configuration/telegram.md
@c9s 
I fixed an doc error i made. Please review
> doc: fix tg doc, needs no notification: block

- pkg/service/backtest.go
> 	backtest : fix auto sync missing the part from last db kiline to

- config/support.yaml
- doc/strategy/support.md
- pkg/strategy/support/strategy.go
- allow setting the interval and the window for trigger MA
- fix support strategy criteria
> strategy: support strategy update

- config/rebalance.yaml
- pkg/strategy/rebalance/strategy.go
> strategy: rebalance: adjust quantity by max amount

- pkg/service/backtest.go
> backtest : finetune for kline scan logic to prevent hanging for

- go.mod
- go.sum
- pkg/exchange/binance/convert.go
- pkg/exchange/binance/parse.go
- pkg/exchange/binance/stream.go
- pkg/exchange/binance/stream_callbacks.go
- pkg/exchange/ftx/stream.go
- pkg/exchange/ftx/stream_message_handler.go
- pkg/exchange/ftx/websocket_messages.go
- pkg/types/bookticker.go
- pkg/types/standardstream_callbacks.go
- pkg/types/stream.go
> exchange/stream : implement booktickerupdate event for ftx and binance

- pkg/cmd/orders.go
- pkg/cmd/trades.go
- pkg/exchange/batch/batch.go
- pkg/exchange/okex/convert.go
- pkg/exchange/okex/parse.go
- pkg/exchange/okex/stream.go
implement okex bookticker event for #388
> exchange/okex : implement bookticker for okex  , #388

- .gitignore
- README.md
- go.mod
- go.sum
> add twitter/telegram badge

- pkg/bbgo/persistence.go
resolve #438
Fix bollmaker backtest error
> Fix: fallback to memory persistence if redis not found

- pkg/cmd/pnl.go
> fix: #287 init environ before querying balance

- pkg/cmd/account.go
- pkg/cmd/balances.go
- pkg/cmd/cancel.go
- pkg/cmd/kline.go
- pkg/cmd/orderbook.go
- pkg/cmd/orders.go
- pkg/cmd/run.go
- pkg/cmd/trades.go
- pkg/cmd/userdatastream.go
- pkg/cmd/utils.go
tested. this should make cobra flag check works
> fix: mark flags as required during PreRunE

- pkg/strategy/support/strategy.go
do not submit order if current position < market.MinQuantity
> fix support strategy

- .github/workflows/release.yml
- Makefile
> feature: add github release flow for dnum

- pkg/bbgo/order_execution.go
- pkg/cmd/backtest.go
- pkg/strategy/bollgrid/strategy.go
- pkg/strategy/emastop/strategy.go
- pkg/strategy/flashcrash/strategy.go
- pkg/strategy/support/strategy.go
- pkg/strategy/xmaker/strategy.go
resolve #482 
add signal handling in backtest.
> feature: add CancelOrders and CancelOrdersTo to executor

- README.md
- pkg/exchange/binance/exchange.go
- pkg/service/order.go
- pkg/service/sync.go
options:
1. use environment variable
2. define it in config yaml
also, what is the influence of our db data once this option is enabled?  
anyway to separate them?
> add binance paper trade endpoint

- config/rebalance.yaml
- pkg/strategy/rebalance/strategy.go
- Rebalance on KLine closed
- Add dry-run option
> strategy: rebalance on KLine closed

- pkg/bbgo/interact.go
- pkg/interact/reply.go
- pkg/interact/slack.go
- pkg/interact/telegram.go
- pkg/strategy/support/strategy.go
- pkg/types/strategy_status.go
strategy: add StrategyController functions to support strategy
interact: add StrategyController interface to control strategies from telegram bot
> feature: strategy controller

- pkg/bbgo/interact.go
separate strategy filtering and button generation
> separate strategy filtering and button generation

- README.md
- doc/README.md
- doc/topics/dnum-binary.md
- scripts/download-dnum.sh
- scripts/setup-bollgrid-dnum.sh
- scripts/setup-bollgrid.sh
- scripts/setup-dnum.sh
- scripts/setup-grid-dnum.sh
> update: readme for dnum. fix: script for curl downloading

- doc/development/indicator.md
- pkg/bbgo/marketdatastore.go
- pkg/bbgo/marketdatastore_callbacks.go
- pkg/cmd/backtest.go
- pkg/indicator/ad.go
- pkg/indicator/boll.go
- pkg/indicator/ewma.go
- pkg/indicator/line.go
- pkg/indicator/macd.go
- pkg/indicator/rsi.go
- pkg/indicator/sma.go
- pkg/indicator/stoch.go
- pkg/indicator/vwap.go
- pkg/indicator/vwma.go
- pkg/types/float_slice.go
- pkg/types/indicator.go
- pkg/types/indicator_test.go
- pkg/types/kline.go
add pinescript series interface and several functions
> feature: add pinescript series interface

- doc/topics/grpc.md
https://github.com/ktr0731/evans#installation
> doc: add brew tap command to grpc doc

- pkg/indicator/ad.go
- pkg/indicator/macd.go
- pkg/indicator/obv.go
- pkg/indicator/rsi.go
- pkg/indicator/stoch.go
- pkg/indicator/vwap.go
The indicators calculated both the second last value, and the last value on each kLine update.
> improved indicators

- pkg/strategy/bollmaker/strategy.go
Add StrategyController to bollmaker so user can stop/resume bollmaker strategy
> Add StrategyController to bollmaker

- pkg/backtest/matching.go
- pkg/bbgo/config.go
- pkg/strategy/ewoDgtrd/strategy.go
resolve https://github.com/c9s/bbgo/issues/509  
also try to deduct the fee from trade to prevent backtesting balance issue
> fix: rename EVWMP to VWEMP, fix backtesting fee

- pkg/interact/auth.go
> refine auth message

- pkg/bbgo/session.go
- pkg/types/interval.go
Could create bollinger band with interval, the window and bandwidth
> indicator: Support difference bandwidth on boll indicator and can dynamic create BOLL

- pkg/strategy/bollmaker/strategy.go
- Update bollmaker to support new strategy controller
> strategy: Update bollmaker to support new strategy controller

- doc/development/indicator.md
- doc/development/series.md
> add Series documentation

- Dockerfile
> fix: golang version in Dockerfile

- Dockerfile
fix installation of sqlite3 in Docker image.
> fix: sqlite3 compilation

- config/bollmaker.yaml
- pkg/strategy/bollmaker/strategy.go
Dynamic spread is an experimental feature.
Enables the automatic adjustment to bid and ask spread.
> feature: bollmaker dynamic spread

- apps/backtest-report/components/TradingViewChart.tsx
- config/ewo_dgtrd.yaml
- pkg/backtest/exchange.go
- pkg/backtest/matching.go
- pkg/service/backtest.go
- pkg/strategy/ewoDgtrd/heikinashi.go
- pkg/strategy/ewoDgtrd/strategy.go
- pkg/strategy/ewoDgtrd/trylock.go
- pkg/strategy/ewoDgtrd/trylock_18.go
- pkg/types/position.go
fix: non-handled split between kline prev close -> current open
fix: ewo entry, ewo average price calculation
> Fix/ewo entry, backtest

- pkg/strategy/bollmaker/dynamic_spread.go
- pkg/strategy/bollmaker/strategy.go
- pkg/types/position.go
> fix: bollmaker: fix short position order

- pkg/bbgo/session.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/max/exchange.go
- pkg/types/exchange.go
> improve: apply default exchange fee rate

- config/pivotshort.yaml
- pkg/strategy/pivotshort/strategy.go
> pivotshort: clean up strategy

- .gitignore
- apps/backtest-report/components/ReportDetails.tsx
- apps/backtest-report/components/ReportNavigator.tsx
- apps/backtest-report/components/TradingViewChart.tsx
- apps/backtest-report/pages/index.tsx
> Improve backtest report ui

- pkg/service/backtest.go
safely defer close / rollback on queries/ transactions
otherwise the db will be locked
> fix: close / rollback queries/transactions on error

- pkg/bbgo/interact.go
- pkg/bbgo/interact_test.go
- pkg/strategy/support/strategy.go
> interact: fix missing make()

- pkg/backtest/matching.go
- pkg/backtest/matching_test.go
- pkg/bbgo/order_execution.go
- pkg/cmd/builtin.go
- pkg/strategy/dca/strategy.go
fixes: #673 
This test case is used for verifying the order update trigger times.
> fix: fix duplicated filled order update callbacks in backtest

- pkg/indicator/drift.go
- pkg/indicator/drift_test.go
- fix divided by zero error
- add test case
> fix: check for div zero in drift indicator

- pkg/types/position.go
> fix: calcualte fee in quote only when fee is not zero

- config/pivotshort-ETHUSDT.yaml
- config/pivotshort.yaml
- pkg/backtest/matching.go
- pkg/bbgo/notifier.go
- pkg/indicator/pivot.go
- pkg/strategy/pivotshort/strategy.go
- pkg/types/position.go
open the short position with market sell when breaks previous pivot low only
.
> strategy: pivotshort: improve short position trigger

- .github/workflows/go.yml
- .gitignore
- codecov.yml
- pkg/depth/buffer.go
- pkg/depth/buffer_test.go
- pkg/util/reonce_test.go
feature: add codecoverage and add race detection in go test
fix: fix race conditions in codebase
> ci: codecoverage

- frontend/api/bbgo.js
- frontend/components/AddExchangeSessionForm.js
- frontend/components/ConfigureDatabaseForm.js
- frontend/components/ConfigureGridStrategyForm.js
- frontend/components/ConnectWallet.js
- frontend/components/ExchangeSessionTabPanel.js
- frontend/components/ReviewSessions.js
- frontend/components/ReviewStrategies.js
- frontend/components/SaveConfigAndRestart.js
- frontend/components/SideBar.js
- frontend/components/TotalAssetsDetails.js
- frontend/components/TotalAssetsPie.js
- frontend/components/TotalAssetsSummary.js
- frontend/components/TradingVolumeBar.js
- frontend/components/TradingVolumePanel.js
- frontend/layouts/DashboardLayout.js
- frontend/layouts/PlainLayout.js
- frontend/next.config.js
- frontend/pages/_app.tsx
- frontend/pages/_document.js
- frontend/pages/api/hello.js
- frontend/pages/connect/index.js
- frontend/pages/index.tsx
- frontend/pages/orders.js
- frontend/pages/setup/index.js
- frontend/pages/trades.js
- frontend/postcss.config.js
- frontend/src/utils.js
- frontend/tsconfig.json
I ran the `yarn prettier` to format js codes. There's no new function or other change.
> format js code by prettier

- config/ewo_dgtrd.yaml
- pkg/strategy/ewoDgtrd/strategy.go
- add ewo histogram described in the original tv script to help filtering signals.
- use atr * 3 + base line as TP/entry
> strategy: ewo: add histogram

- frontend/api/bbgo.ts
- frontend/layouts/DashboardLayout.js
- frontend/src/utils.js
We can ask bbgo server to executing the sync operation. The operation is throttled.
> feature: on demand sync button

- config/rebalance.yaml
- pkg/strategy/rebalance/strategy.go
- rename methods and variables
- remove ignoreLock option (always get total balance)
- manage active order book without specifying symbol
- remove unused subscriptions
> rebalance: simplify code

- config/rsmaker.yaml
- go.mod
- go.sum
- pkg/cmd/builtin.go
- pkg/strategy/rsmaker/strategy.go
A market maker strategy by @c9s  that detecting Support and Resistance via K-means algorithm in order to cluster key K-lines.
> strategy: rsmaker: initial idea prototype

- apps/backtest-report/components/ReportDetails.tsx
- apps/backtest-report/components/TradingViewChart.tsx
> improve: backtest-report layout improvements, EMA indicators and fixed the clean up issue

- apps/backtest-report/components/TimeRangeSlider/components/Handle.js
- apps/backtest-report/components/TimeRangeSlider/components/KeyboardHandle.js
- apps/backtest-report/components/TimeRangeSlider/components/SliderRail.js
- apps/backtest-report/components/TimeRangeSlider/components/Tick.js
- apps/backtest-report/components/TimeRangeSlider/components/Track.js
- apps/backtest-report/components/TimeRangeSlider/index.jsx
- apps/backtest-report/components/TimeRangeSlider/index.scss
- apps/backtest-report/components/TradingViewChart.tsx
- apps/backtest-report/package.json
- apps/backtest-report/pages/_app.tsx
- apps/backtest-report/pages/_document.tsx
- apps/backtest-report/yarn.lock
- pkg/types/profit.go
> backtest-report: add time range slider

- pkg/backtest/matching_test.go
Signed-off-by: c9s <yoanlin93@gmail.com>
> test: backtest: add order cancel test case

- pkg/types/indicator.go
- pkg/types/indicator_test.go
- pkg/types/seriesbase_imp.go
SeriesExtend:
- softmax
- sigmoid
- entropy
- cross-entropy
add LogisticRegression
Speed up Dot operation
> feature: logistic regression

- pkg/strategy/supertrend/double_dema.go
- pkg/strategy/supertrend/strategy.go
A problem that uses double DEMA object before initialization. Uses newDoubleDema() to setup instead
> strategy/supertrend: fix double dema initialization problem

- pkg/indicator/sma.go
- pkg/indicator/sma_test.go
> fix: sma calculation, length, and add test case

- pkg/backtest/report.go
Before this change, each time when backtest tries to read/write/append output/index.json, it will create an empty .report.lock lock file, acquire the file lock, I/O on index.json, unlock, then delete the lock file.
However, this does not prevent the data race between backtests:
1. backtest A acquire the lock, and finish the works on index.json
2. backtest B wait for the lock
3. backtest A release the lock
4. backtest B acquire the lock
5. backtest A delete .report.lock
6. backtest C want to modify index.json, hence it creates a new .report.lock at the same path, lock on the new lock file
7. index.json is modified by B and C simultaneously since there are multiple lock instances
In POSIX, file deletion is not protected by file locks. While performing optimizer, this problem is very likely …
> backtest: resolve data race on index.json

- pkg/exchange/binance/exchange.go
- pkg/exchange/max/exchange.go
- pkg/fixedpoint/convert.go
- pkg/fixedpoint/dec.go
- pkg/fixedpoint/dec_test.go
- pkg/types/interval.go
- binance sync time
- exchange interval query
- fixedpoint yaml test / fixes
> fix splitted from feature/drift_study

- pkg/optimizer/grid.go
Calculate total number of grid points before optimizer performing backtesting. This make the ETA predictable for users.
> optimizer: calculate total number of grids before testing

- apps/backtest-report/components/TradingViewChart.tsx
- config/drift.yaml
- config/driftBTC.yaml
- go.mod
- go.sum
- pkg/bbgo/interact.go
- pkg/bbgo/notification.go
- pkg/notifier/slacknotifier/slack.go
- pkg/notifier/telegramnotifier/telegram.go
- pkg/strategy/drift/strategy.go
- pkg/types/indicator.go
- pkg/types/trade_stats.go
on every tick, check for the border cases to decide whether to cancel the order or not.
> feature: add smart cancel to drift

- apps/backtest-report/components/TradingViewChart.tsx
- config/drift.yaml
- config/driftBTC.yaml
- go.mod
- go.sum
- pkg/bbgo/interact.go
- pkg/bbgo/notification.go
- pkg/notifier/slacknotifier/slack.go
- pkg/notifier/telegramnotifier/telegram.go
- pkg/strategy/drift/strategy.go
- pkg/types/indicator.go
- pkg/types/trade_stats.go
> Revert "feature: add smart cancel to drift"

- pkg/cmd/hoptimize.go
- pkg/optimizer/hpoptimizer.go
Users can stop worry about long trials. It is now able to stop trials by sending system signal (SIGINT & SIGTERM) and see the report earlier at any time.
> hoptimizer: manually early stop

- config/supertrend.yaml
- pkg/exchange/binance/exchange.go
https://binance-docs.github.io/apidocs/futures/en/#futures-account-balance-v2-user_data
> strategy/supertrend: update example config

- pkg/exchange/binance/convert.go
- pkg/exchange/binance/convert_futures.go
- pkg/exchange/binance/exchange.go
- pkg/exchange/binance/parse.go
- pkg/types/order.go
> binance: fix futures/margin order sync issue

- pkg/cmd/backtest.go
fix exchangeDataSource pass by copy in for loop
> fix backtest output

- pkg/cmd/backtest.go
> feature: write strategy config in the backtest report directory

- pkg/fixedpoint/count.go
- pkg/fixedpoint/filter.go
- pkg/fixedpoint/reduce.go
- pkg/fixedpoint/reduce_test.go
- pkg/fixedpoint/slice.go
- pkg/fixedpoint/slice_test.go
- pkg/types/position.go
- pkg/types/profit.go
- pkg/types/trade_stats.go
This counts profits by orderID
> feature: add fixedpoint.Reducer, Counter and add update stats method on TradeStats

- config/supertrend.yaml
- pkg/strategy/supertrend/draw.go
- pkg/strategy/supertrend/strategy.go
- Add pnl and cumpnl drawing for backtesting
- Pnl and cumpnl commands for tg
> feature: strategy/supertrend: draw pnl on

- pkg/bbgo/trend_ema.go
- pkg/bbgo/trend_ema_test.go
- pkg/strategy/pivotshort/breaklow.go
- pkg/strategy/pivotshort/failedbreakhigh.go
- pkg/strategy/pivotshort/resistance.go
- pkg/strategy/pivotshort/strategy.go
Fix trend EMA and make strategy controller work
> Fix: Pivotshort 

- pkg/accounting/pnl/avg_cost.go
fix panic issue when there is no trade in the backtest
> pnl: fix nil position point issue

- pkg/bbgo/environment.go
- pkg/notifier/telegramnotifier/logrus_look.go
- pkg/notifier/telegramnotifier/telegram.go
- pkg/slack/slacklog/logrus_look.go
add telegram notifier as a logrus hook
> notifier: redirect error, panic, fatal error to telegram

- config/pivotshort.yaml
- pkg/bbgo/order_executor_general.go
- pkg/strategy/pivotshort/breaklow.go
- pkg/strategy/pivotshort/failedbreakhigh.go
- fix fast pivot low filtering
- add fastWindow parameters
- call openPosition method (add more order options)
> strategy/pivotshort: call open position and add more position options

- pkg/bbgo/risk.go
- pkg/bbgo/risk_test.go
- pkg/strategy/pivotshort/failedbreakhigh.go
- pkg/strategy/xnav/strategy.go
- pkg/types/balance.go
- pkg/types/balance_test.go
> fix: fix net asset calculation

- config/trendtrader.yaml
- pkg/cmd/strategy/builtin.go
- pkg/strategy/trendtrader/strategy.go
- pkg/strategy/trendtrader/trend.go
> strategy: add trend trader

- config/driftBTC.yaml
- pkg/indicator/wdrift.go
- pkg/strategy/drift/strategy.go
> fix: drift minus weight, preloaded kline not enough

- pkg/bbgo/order_executor_general.go
- pkg/bbgo/order_processor.go
fix the max borrowable amount issue
> improve: bbgo: use margin asset borrowable amount to adjust the quantity

- config/drift.yaml
- config/driftBTC.yaml
- pkg/bbgo/order_executor_general.go
- pkg/bbgo/risk.go
- pkg/bbgo/scale_test.go
- pkg/dynamic/field.go
- pkg/dynamic/field_test.go
- pkg/fixedpoint/const.go
- pkg/strategy/drift/strategy.go
- pkg/strategy/pivotshort/breaklow.go
- pkg/strategy/pivotshort/failedbreakhigh.go
- pkg/types/error.go
- pkg/types/filter.go
- pkg/types/indicator.go
- pkg/types/indicator_test.go
- pkg/types/seriesbase_imp.go
feature: add series.filter
fix: fixedpoint.Four
fix: modifiable for embedded fields
refactor: change drift to use openPosition
refactor: modify openPosition behavior
> improve: series.Filter + drift.openPosition + modify openPosition behavior + fix consts

- pkg/strategy/drift/strategy.go
fix wrong tag in drift
also try to support Interval=1m from setting.
> fix: wrong tag in drift

- pkg/dynamic/print_strategy.go
- pkg/strategy/drift/output.go
- pkg/strategy/drift/strategy.go
- pkg/strategy/elliottwave/output.go
- pkg/strategy/elliottwave/strategy.go
> feature: add config dump / param dump / param modify for elliottwave

- config/drift.yaml
- config/driftBTC.yaml
- pkg/bbgo/order_executor_general.go
- pkg/strategy/drift/stoploss.go
- pkg/strategy/drift/strategy.go
fix bugs in drift.
export quantity in OpenPositionOptions.
> refactor: extract stoploss, fix highest/lowest in trailingExit

- pkg/bbgo/activeorderbook.go
- pkg/bbgo/order_executor_general.go
- pkg/strategy/elliottwave/strategy.go
in 1s strategy, we need this function to disable blocking query on all the open orders from rest api.
> add cancelNoWait

- pkg/bbgo/risk.go
remove balance check in the futures part of CalculateBaseQuantity()
> fix/risk: remove balance check in CalculateBaseQuantity()

- pkg/types/indicator.go
fix 1s timeframe in types.indicator
> fix: indicator timeframe 1s

- pkg/notifier/telegramnotifier/telegram.go
feature: add goroutine for consuming telegram notify tasks.
all the Notify/SendPhoto apis become async.
> feature: telegram notify to become async

- config/harmonic.yaml
- pkg/strategy/harmonic/strategy.go
strategy: improve harmonic by adding [HMM](https://tr8dr.github.io/HMMFiltering/) filter to denoise shark signal
> strategy: improve harmonic by adding HMM filter to denoise shark signal

- pkg/backtest/report.go
- pkg/cmd/backtest.go
- pkg/optimizer/config.go
- pkg/optimizer/grid.go
- pkg/optimizer/hpoptimizer.go
- Optimizer add profitFactor optimization
- Optimization value uses float64 instead to save memory and boost performance
- Optimization metric function: profitFactor * 0.9 + winningRatio * 0.1
> optimizer / hoptimizer add new object

- config/supertrend.yaml
> strategy/supertrend: update supertrend config

- doc/development/series.md
add documentation on SeriesExtend
> doc: add series extend documentation

- .github/workflows/go.yml
- config/grid2-max.yaml
- config/grid2.yaml
- pkg/cmd/strategy/builtin.go
- pkg/exchange/binance/binanceapi/client_test.go
- pkg/fixedpoint/dec.go
- pkg/fixedpoint/dec_dnum_test.go
- pkg/service/backtest_test.go
- pkg/strategy/grid2/grid.go
- pkg/strategy/grid2/grid_test.go
- pkg/strategy/grid2/strategy.go
- pkg/strategy/grid2/strategy_test.go
- pkg/strategy/trendtrader/trend.go
- pkg/types/market.go
- pkg/types/market_test.go
> strategy: grid2 [part 1] - initializing grid orders

- README.md
- scripts/sync_time.sh
Useful script to help users synchronize the system date with Binance servers.
> feature: add sync_time.sh utility

- .github/workflows/docker.yml
> feature: push to quay.io

- config/grid2-max.yaml
- pkg/bbgo/activeorderbook.go
- pkg/exchange/max/exchange.go
- pkg/strategy/grid2/mocks/order_executor.go
- pkg/strategy/grid2/strategy.go
- pkg/types/order.go
- pkg/types/sort.go
> strategy: grid2: recover grid orders [part 2]

- README.md
Trading-GPT is a trading bot based on [bbgo](https://github.com/c9s/bbgo) and [ChatGPT](https://github.com/yubing744/chatgpt-go). I think this is a good example of a private bbgo strategy.
> feat: add private strategy demo trading-gpt

- pkg/service/memory.go
There are multiple goroutines accessing the same memory store. To prevent data racing, mutex is required.
> FIX: add mutex in memory store

- pkg/strategy/grid2/pin_order_map.go
- pkg/strategy/grid2/strategy.go
- pkg/strategy/grid2/strategy_test.go
After fixing FormatString, we can use Pin as our key
> FEATURE: make PinOrderMap's key from string to Pin

- pkg/exchange/max/maxapi/restapi.go
- pkg/util/backoff/general.go
> FIX: maxapi: use sync.Once to prevent duplicated update and avoid update negative offset

- pkg/types/indicator.go
- pkg/types/indicator_test.go
Add int32/int64/int support on:
- Dot
- Add
- Mul
> fix: some types and operations in SeriesExtended are not supported

- config/xalign.yaml
- pkg/cmd/strategy/builtin.go
- pkg/strategy/xalign/strategy.go
- pkg/strategy/xnav/strategy.go
- pkg/types/balance.go
This is a strategy for aligning balances
> FEATURE: [strategy] add xalign strategy

- pkg/strategy/grid2/metrics.go
- pkg/strategy/grid2/recover.go
- pkg/strategy/grid2/strategy.go
Remove a high cardinality metric.
> MINOR: [grid2] delete order prices metric

- pkg/bbgo/exit.go
since we've set it default to true
> CHORE: bbgo: rename env ENABLE_MARKET_TRADE_STOP to DISABLE_MARKET_TRADE_STOP

- go.sum
- pkg/exchange/okex/convert.go
- pkg/exchange/okex/exchange.go
- pkg/exchange/okex/okexapi/client.go
- pkg/exchange/okex/okexapi/client_test.go
- pkg/exchange/okex/okexapi/trade.go
- pkg/exchange/okex/query_order_test.go
- pkg/testutil/auth.go
add some unit test for OKEX exchange
> TEST: add unit test for okex exchange

- pkg/exchange/bybit/stream.go
- pkg/exchange/bybit/stream_callbacks.go
- pkg/exchange/bybit/stream_test.go
- pkg/exchange/bybit/types.go
- pkg/exchange/bybit/types_test.go
REMARK: The order id, IsMaker, fee, fee currency are not supported
> FEATURE: [bybit] support market trade

- pkg/risk/riskcontrol/circuit_break.go
- pkg/strategy/common/strategy.go
- pkg/strategy/fixedmaker/strategy.go
We need a public method to check if it is halted or not.
> CHORE: add IsHalted method to common.Strategy for CircuitBreakRiskControl

- pkg/exchange/okex/convert.go
- pkg/exchange/okex/exchange.go
- pkg/exchange/okex/query_kline_test.go
- pkg/exchange/okex/types.go
1. Extract from my old PR - just add supported interval.
2. add its unit test.
> FEATURE: add supported interval for okex

- pkg/exchange/bybit/stream.go
- pkg/exchange/bybit/stream_test.go
- pkg/types/stream.go
https://bybit-exchange.github.io/docs/changelog/v5#websocket-api
> FEATURE: [BYBIT] support order book depth 200 on bybit

- config/random.yaml
- pkg/strategy/random/strategy.go
> REFACTOR: [random] remove adjustQuantity from config

- README.md
Modified the language of README file.
Better language helps in understanding and increases productivity.
I'm happy to contribute to this project.
> Modified README.md file's language.

- pkg/exchange/bybit/stream.go
- pkg/types/stream.go
Use the same `conn` to avoid concurrent write issues. So i move the exchange level ping function into the stream ping function.
> REFACTOR: [stream] move ping into stream level

- CODE_OF_CONDUCT.md
Grammatical errors where there in the CODE_OF_CONDUCT.md file
> grammatical error in the code_of_conduct file

- config/rebalance.yaml
- pkg/strategy/rebalance/multi_market_strategy.go
- pkg/strategy/rebalance/position_map.go
- pkg/strategy/rebalance/profit_stats_map.go
- pkg/strategy/rebalance/strategy.go
- submit one order at a time
- cron
> REFACTOR: [rebalance] submit one order at a time

- README.md
Grammatical error were their in the readme.md file
> grammatical errors in the README.md

- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
first commit from https://github.com/c9s/bbgo/pull/1378
> REFACTOR: [bitget] add rate limiter for account, ticker

- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
https://bitgetlimited.github.io/apidoc/en/spot/#get-all-tickers
> FEATURE: [bitget] add query tickers api

- pkg/exchange/bybit/market_info_poller.go
The total number of logs is 6*24 in one day, and these logs are very helpful for debugging the fee rate.
> CHORE: [bybit] print fee rate log

- pkg/exchange/bitget/bitgetapi/client.go
- pkg/exchange/bitget/bitgetapi/v2/client.go
- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/exchange.go
- pkg/exchange/bitget/stream.go
- pkg/exchange/bitget/stream_callbacks.go
- pkg/exchange/bitget/stream_test.go
- pkg/exchange/bitget/types.go
https://www.bitget.com/api-doc/spot/websocket/private/Account-Channel
> FEATURE: [bitget]add balance event

- pkg/exchange/bitget/stream.go
- pkg/exchange/bybit/stream.go
- pkg/exchange/bybit/types.go
- pkg/exchange/bybit/types_test.go
- pkg/types/stream.go
The ping/pong event is like spam that attacks subscribers, so I ignore it.
> REFACTOR: [stream] skip pong event on emitting raw message

- migrations/mysql/20231123125402_fix_order_status_length.sql
- migrations/sqlite3/20231123125402_fix_order_status_length.sql
- pkg/migrations/mysql/20231123125402_fix_order_status_length.go
- pkg/migrations/sqlite3/20231123125402_fix_order_status_length.go
```
Error 1406: Data too long for column 'status' at row 1
```
PARTIALLY_FILLED
> FIX: fix order status length

- .github/workflows/go.yml
- .github/workflows/golang-lint.yml
- pkg/bbgo/activeorderbook.go
- pkg/strategy/xdepthmaker/strategy.go
- pkg/strategy/xdepthmaker/strategy_test.go
- pkg/types/orderbook.go
- pkg/types/price_volume_slice.go
- pkg/types/sliceorderbook_test.go
- place orders with balance quota calculation
- wait for authed event
- clean up open orders on start
> IMPROVE: [xdepthmaker] add more improvements

- pkg/exchange/bitget/convert.go
- pkg/exchange/bitget/convert_test.go
- pkg/exchange/bitget/stream_test.go
- pkg/exchange/bitget/types.go
> FIX: [bitget] fix price is zero when order not executed

- config/dca2.yaml
- pkg/exchange/max/maxapi/v3/get_wallet_open_orders_request_requestgen.go
- pkg/strategy/dca2/debug.go
- pkg/strategy/dca2/open_position_test.go
- pkg/strategy/dca2/recover.go
- pkg/strategy/dca2/recover_test.go
- pkg/strategy/dca2/state.go
- pkg/strategy/dca2/strategy.go
- pkg/types/sort.go
FEATURE: support recover
FEATURE: add orders into orderStore and recover position
FEATURE: recover position/budget
> FEATURE: [dca2] run state machine

- pkg/backtest/exchange.go
- pkg/cmd/backtest.go
- pkg/migrations/mysql/20231221121432_add_futures_klines.go
- pkg/migrations/sqlite3/20231221121432_add_futures_klines.go
- pkg/service/backtest.go
tables for futures data
sync futures data
backtest with futures data
> WIP: feature: sync futures data and backtest with them

- pkg/strategy/xgap/strategy.go
- avoid canceling the order that has already been fulfilled
- remove unused constant
> FIX: [xgap] fix order cancel error

- .github/workflows/go.yml
https://github.com/morphy2k/revive-action/issues/125
https://github.com/mgechev/revive/issues/956
> FIX: specify the version of morphy2k/revive-action to 2.5.4

- pkg/exchange/okex/parse.go
- pkg/exchange/okex/parse_test.go
- pkg/exchange/okex/stream.go
- pkg/exchange/okex/stream_callbacks.go
- pkg/exchange/okex/stream_test.go
K Line is currently not functioning because it is required to subscribe to another URL: wss://ws.okx.com:8443/ws/v5/business.
So, I simply refactor it.
> REFACTOR: [okx] refactor book and kline

- pkg/strategy/xgap/strategy.go
or 
```
func (s *Strategy) Initialize() error {
log = log.WithField("symbol", s.Symbol)
return nil
}
```
> CHORE: [xgap] print currency when insufficient balance

- README.md
- README.zh_TW.md
Also, added links in README.md / README.zh_TW.md
kudos to https://zh.wikibooks.org/zh/%E5%A4%A7%E9%99%86%E5%8F%B0%E6%B9%BE%E8%AE%A1%E7%AE%97%E6%9C%BA%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7%E8%A1%A8
> DOCS: Translate the README into zh_TW

- pkg/bbgo/indicator_set.go
- pkg/indicator/v2/keltner.go
adding a simple keltner channel indicator implementation
> FEATURE: [INDICATOR] keltner channel

- pkg/exchange/okex/okexapi/client.go
https://www.okx.com/docs-v5/en/#error-code-rest-api-public
> FEATURE: [okx] add response validation func

- pkg/exchange/okex/exchange.go
- pkg/exchange/okex/exchange_test.go
https://www.okx.com/docs-v5/en/#order-book-trading-trade-post-place-order
> FIX: [okx] allow char in place order

- pkg/strategy/xalign/strategy.go
> FIX: [xalign] check if the quote balance will be used up and below the expected balance

- pkg/cmd/orders.go
fix issue https://github.com/c9s/bbgo/issues/1037
> FIX: issue #1037, get-order command error

- pkg/strategy/autobuy/strategy.go
- pkg/strategy/common/strategy.go
- pkg/strategy/emacross/strategy.go
- pkg/strategy/fixedmaker/strategy.go
- pkg/strategy/liquiditymaker/strategy.go
- pkg/strategy/random/strategy.go
- pkg/strategy/rebalance/strategy.go
- pkg/strategy/rsicross/strategy.go
- pkg/strategy/scmaker/strategy.go
- pkg/strategy/wall/strategy.go
- pkg/strategy/xfixedmaker/strategy.go
- pkg/strategy/xgap/strategy.go
> FIX: disable bbgo.sync in common strategy to fix xgap

- pkg/types/order.go
fix #1624 , with some historical reasons.
> fix: tg order decimal

- pkg/strategy/xmaker/strategy.go
- pkg/types/position.go
the missing metrics label is causing panic
> FIX: [xmaker] position metrics missing label

- doc/configuration/telegram.md
just a minor typo fix to prevent confusing in telegram doc
> DOC: fix env name

- pkg/bbgo/trader.go
The initialize() method is called twice from different places
> FIX: [bbgo] fix the defaults / initialize steps

- pkg/exchange/binance/parse.go
- pkg/exchange/binance/parse_test.go
- pkg/server/routes.go
- pkg/strategy/grid2/strategy.go
https://developers.binance.com/docs/derivatives/usds-margined-futures/user-data-streams/Event-Trade-Lite
> feature: add binance TRADE_LITE event

- README.md
- README.zh_TW.md
Small PR - Commit e310ea9e4e6460930c0346f1c37887ffd644c4bd moved the `strategy.go` file. This PR adjusts sources to changes.
> fix: update `strategy.go` reference

- pkg/exchange/okex/exchange.go
Previously, we used the GET [/api/v5/trade/fills-history](https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-transaction-details-last-3-months) API, which might not provide real-time trade result. 
Now we have switched to GET [/api/v5/trade/fills](https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-transaction-details-last-3-days), which should allow us to obtain more real-time trades.
> MAJOR: [okx] use get 3 days query trade api

- pkg/exchange/coinbase/parse.go
- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_callbacks.go
- pkg/exchange/coinbase/stream_messages.go
Implement message parser for coinbase websocket feeds.
> FEATURE: [exchange] implement message parsing for Coinbase websocket messages

- pkg/exchange/coinbase/api/v1/get_orders_request.go
- pkg/exchange/coinbase/convert.go
> FIX: [exchange] (coinbase) fill missing SubmitOrder

- pkg/core/orderstore.go
- pkg/types/order.go
Improve order update logic and encapsulate update functionality.
It's preparation work to simplify the implementation and integration with Coinbase Websocket feeds.
> FIX: [core] Improve order update logic and encapsulate update functionality

- pkg/types/indicator.go
- pkg/types/sort.go
make function comments match function names
> chore: make function comments match function names

- pkg/exchange/coinbase/parse.go
- pkg/exchange/coinbase/stream.go
- pkg/exchange/coinbase/stream_callbacks.go
- pkg/exchange/coinbase/stream_handlers.go
- pkg/exchange/coinbase/stream_messages.go
- pkg/exchange/coinbase/stream_test.go
- Add `subscriptions` handling
- it's the confirmation message send by Coinbase Websocket
- Add tests for stream
> FIX: [coinbase] add stream tests and fix bugs

- pkg/exchange/coinbase/stream_messages.go
> FIX: [coinbase] add trade id for match and tick message

- pkg/service/reflect.go
- pkg/service/sync_task.go
> FIX: [sync service] move self-trade patch after sortRecordsAscending call

- pkg/exchange/bitget/exchange.go
- pkg/exchange/okex/exchange.go
- pkg/service/sync.go
- pkg/service/sync_task.go
- pkg/service/trade.go
- pkg/util/logger.go
> MINOR: [sync][okx] add more log

- pkg/exchange/bitget/bitgetapi/v2/place_order_request_requestgen.go
- pkg/exchange/bitget/exchange.go
- pkg/strategy/xgap/strategy.go
> IMPROVE: [bitget] improve bitget time in force support

- pkg/strategy/xdepthmaker/metrics.go
- Remove max price spacing matrics
- the metric is not stable if there is abnormal open orders (sell order with very high price or buy order with very low price)
> FIX: [metrics] remove max price spacing metrics

- pkg/strategy/xgap/strategy.go
- pkg/strategy/xgap/strategy_test.go
- pkg/types/position.go
- pkg/types/position_test.go
When adjusting position is possible, place corresponding orders.
> FIX: [xgap] place adjust position orders

- pkg/strategy/xmaker/metrics.go
- pkg/strategy/xmaker/spreadmaker.go
- pkg/strategy/xmaker/strategy.go
- add covered position metrics
- use uncovered position to place spread maker order
- return covered position for any trade
> FIX: [xmaker] uncovered position fix

- pkg/service/sync_task.go
This reverts commit 38575d738f76c59ded3134f44483b25259b29595, reversing changes made to ff85c85467edfdf1e7dbc9d255b9192ccd5c4541.
> REVERT:[sync] Merge pull request #2028 from c9s/dboy/hotfix-sync-upsert-symbols

- pkg/core/klinedriver/bucket.go
- pkg/core/klinedriver/bucket_test.go
- pkg/core/klinedriver/klinebuilder.go
- pkg/core/klinedriver/klinebuilder_test.go
- pkg/core/klinedriver/tick_klinedriver.go
- pkg/core/klinedriver/tick_klinedriver_test.go
- pkg/types/kline.go
Example KLine outputs
```
time="2025-05-08T16:29:44+08:00" KLine: {GID:0 Exchange:coinbase Symbol:BTCUSDT StartTime:2025-05-08 08:29:00 +0000 UTC EndTime:2025-05-08 08:29:37.553677 +0000 UTC Interval:1m Open:99532.63 Close:99532.63 High:99532.63 Low:99532.63 Volume:0.10572354 QuoteVolume:10522.94198906 TakerBuyBaseAssetVolume:0.10572354 TakerBuyQuoteAssetVolume:10522.94198906 LastTradeID:30405634 NumberOfTrades:15 Closed:false}\n"
time="2025-05-08T16:29:54+08:00" KLine: {GID:0 Exchange:coinbase Symbol:BTCUSDT StartTime:2025-05-08 08:29:00 +0000 UTC EndTime:2025-05-08 08:29:37.553677 +0000 UTC Interval:1m Open:99532.63 Close:99532.63 High:99532.63 Low:99532.63 Volume:0.10572354 QuoteVolume:10522.94198906 TakerBuyBaseAssetVolume:0.10572354 TakerBuyQuoteAssetVolume:10522.94198906 …
```
> FEATURE: [core] KLineBuilder and tick-based kline driver

- .github/workflows/go.yml
- pkg/exchange/max/maxapi/restapi.go
- pkg/util/apikey/balancer.go
- pkg/util/apikey/balancer_test.go
- pkg/util/apikey/entry.go
- pkg/util/apikey/loader.go
- pkg/util/apikey/loader_test.go
Implement a api key rotator (balancer) with a custom format pattern loader
> FEATURE: implement apikey rotator

- pkg/types/indicator.go
- pkg/types/indicator_test.go
- pkg/types/series.go
- pkg/types/seriesbase_imp.go
- pkg/types/trade_stats.go
Add OLS. Need test cases to compare with the result from python.
> feature: add Ordinary Least Square for series

- pkg/datatype/floats/funcs.go
- pkg/datatype/floats/funcs_test.go
- pkg/datatype/floats/slice.go
- pkg/datatype/floats/slice_test.go
Add utility functions to generate floats with random numbers.
> feature: add np.random functions to generate rand arrays

- pkg/testing/testhelper/assert_priceside.go
> chore: fix problematic comment

- pkg/bbgo/session.go
- pkg/strategy/xmaker/repay.go
- pkg/strategy/xmaker/signal/signal.go
- pkg/strategy/xmaker/signal/signal_test.go
- pkg/strategy/xmaker/strategy.go
- pkg/types/market.go
- market maps are shared, allocate a new market map for merging.
- use shared accountValueCalculator 
- fix signal weight parsing
> FIX: [xmaker] fix multiple issues

- pkg/strategy/xalign/metrics.go
- pkg/strategy/xalign/strategy.go
- tracking quantity/amount delta of assets
- Introduce new config `skipAlignOnAnyActiveTransfer`
- If set true, the strategy will skip alignment if there is any active transfer of any currency
> UPDATE: [xalign] implement metrics tracking for balance deltas
